package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Acceso generated by hbm2java
 */
@Entity
@Table(name = "acceso", catalog = "itaid")
public class Acceso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AccesoId id;

	public Acceso() {
	}

	public Acceso(AccesoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "node", column = @Column(name = "node", nullable = false, length = 100)),
			@AttributeOverride(name = "action", column = @Column(name = "action", nullable = false, length = 25)),
			@AttributeOverride(name = "perfilId", column = @Column(name = "perfil_id", nullable = false)) })
	public AccesoId getId() {
		return this.id;
	}

	public void setId(AccesoId id) {
		this.id = id;
	}

}
