package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivoAsignacion generated by hbm2java
 */
@Entity
@Table(name = "activo_asignacion", catalog = "itaid")
public class ActivoAsignacion implements java.io.Serializable {

	private int id;
	private int activoId;
	private int tipoasignacion;
	private int asignadoId;
	private int motivo;
	private Date inicia;
	private Date termina;
	private boolean vigente;

	public ActivoAsignacion() {
	}

	public ActivoAsignacion(int id, int activoId, int tipoasignacion, int asignadoId, int motivo, Date inicia,
			Date termina, boolean vigente) {
		this.id = id;
		this.activoId = activoId;
		this.tipoasignacion = tipoasignacion;
		this.asignadoId = asignadoId;
		this.motivo = motivo;
		this.inicia = inicia;
		this.termina = termina;
		this.vigente = vigente;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "activo_id", nullable = false)
	public int getActivoId() {
		return this.activoId;
	}

	public void setActivoId(int activoId) {
		this.activoId = activoId;
	}

	@Column(name = "tipoasignacion", nullable = false)
	public int getTipoasignacion() {
		return this.tipoasignacion;
	}

	public void setTipoasignacion(int tipoasignacion) {
		this.tipoasignacion = tipoasignacion;
	}

	@Column(name = "asignado_id", nullable = false)
	public int getAsignadoId() {
		return this.asignadoId;
	}

	public void setAsignadoId(int asignadoId) {
		this.asignadoId = asignadoId;
	}

	@Column(name = "motivo", nullable = false)
	public int getMotivo() {
		return this.motivo;
	}

	public void setMotivo(int motivo) {
		this.motivo = motivo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inicia", nullable = false, length = 10)
	public Date getInicia() {
		return this.inicia;
	}

	public void setInicia(Date inicia) {
		this.inicia = inicia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "termina", nullable = false, length = 10)
	public Date getTermina() {
		return this.termina;
	}

	public void setTermina(Date termina) {
		this.termina = termina;
	}

	@Column(name = "vigente", nullable = false)
	public boolean isVigente() {
		return this.vigente;
	}

	public void setVigente(boolean vigente) {
		this.vigente = vigente;
	}

}
