package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bitacorasites generated by hbm2java
 */
@Entity
@Table(name = "bitacorasites", catalog = "itaid")
public class Bitacorasites implements java.io.Serializable {

	private Integer idactividad;
	private int iduser;
	private Date horario;
	private String sitenombre;
	private int piso;
	private String comentpiso;
	private String observaciones;
	private int usercaptura;
	private Date fechacaptura;
	private int useractualiza;
	private Date fechauditoria;

	public Bitacorasites() {
	}

	public Bitacorasites(int iduser, Date horario, String sitenombre, int piso, String comentpiso, String observaciones,
			int usercaptura, Date fechacaptura, int useractualiza, Date fechauditoria) {
		this.iduser = iduser;
		this.horario = horario;
		this.sitenombre = sitenombre;
		this.piso = piso;
		this.comentpiso = comentpiso;
		this.observaciones = observaciones;
		this.usercaptura = usercaptura;
		this.fechacaptura = fechacaptura;
		this.useractualiza = useractualiza;
		this.fechauditoria = fechauditoria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idactividad", unique = true, nullable = false)
	public Integer getIdactividad() {
		return this.idactividad;
	}

	public void setIdactividad(Integer idactividad) {
		this.idactividad = idactividad;
	}

	@Column(name = "iduser", nullable = false)
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "horario", nullable = false, length = 19)
	public Date getHorario() {
		return this.horario;
	}

	public void setHorario(Date horario) {
		this.horario = horario;
	}

	@Column(name = "sitenombre", nullable = false, length = 50)
	public String getSitenombre() {
		return this.sitenombre;
	}

	public void setSitenombre(String sitenombre) {
		this.sitenombre = sitenombre;
	}

	@Column(name = "piso", nullable = false)
	public int getPiso() {
		return this.piso;
	}

	public void setPiso(int piso) {
		this.piso = piso;
	}

	@Column(name = "comentpiso", nullable = false, length = 100)
	public String getComentpiso() {
		return this.comentpiso;
	}

	public void setComentpiso(String comentpiso) {
		this.comentpiso = comentpiso;
	}

	@Column(name = "observaciones", nullable = false, length = 100)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "usercaptura", nullable = false)
	public int getUsercaptura() {
		return this.usercaptura;
	}

	public void setUsercaptura(int usercaptura) {
		this.usercaptura = usercaptura;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacaptura", nullable = false, length = 19)
	public Date getFechacaptura() {
		return this.fechacaptura;
	}

	public void setFechacaptura(Date fechacaptura) {
		this.fechacaptura = fechacaptura;
	}

	@Column(name = "useractualiza", nullable = false)
	public int getUseractualiza() {
		return this.useractualiza;
	}

	public void setUseractualiza(int useractualiza) {
		this.useractualiza = useractualiza;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechauditoria", nullable = false, length = 19)
	public Date getFechauditoria() {
		return this.fechauditoria;
	}

	public void setFechauditoria(Date fechauditoria) {
		this.fechauditoria = fechauditoria;
	}

}
