package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BitacorasitesactividadesId generated by hbm2java
 */
@Embeddable
public class BitacorasitesactividadesId implements java.io.Serializable {

	private int idactividad;
	private int idSite;

	public BitacorasitesactividadesId() {
	}

	public BitacorasitesactividadesId(int idactividad, int idSite) {
		this.idactividad = idactividad;
		this.idSite = idSite;
	}

	@Column(name = "idactividad", nullable = false)
	public int getIdactividad() {
		return this.idactividad;
	}

	public void setIdactividad(int idactividad) {
		this.idactividad = idactividad;
	}

	@Column(name = "idSite", nullable = false)
	public int getIdSite() {
		return this.idSite;
	}

	public void setIdSite(int idSite) {
		this.idSite = idSite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BitacorasitesactividadesId))
			return false;
		BitacorasitesactividadesId castOther = (BitacorasitesactividadesId) other;

		return (this.getIdactividad() == castOther.getIdactividad()) && (this.getIdSite() == castOther.getIdSite());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdactividad();
		result = 37 * result + this.getIdSite();
		return result;
	}

}
