package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CategoriaEventos generated by hbm2java
 */
@Entity
@Table(name = "categoria_eventos", catalog = "itaid")
public class CategoriaEventos implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private int categoriaPid;
	private boolean status;

	public CategoriaEventos() {
	}

	public CategoriaEventos(String descripcion, int categoriaPid, boolean status) {
		this.descripcion = descripcion;
		this.categoriaPid = categoriaPid;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "categoria_pid", nullable = false)
	public int getCategoriaPid() {
		return this.categoriaPid;
	}

	public void setCategoriaPid(int categoriaPid) {
		this.categoriaPid = categoriaPid;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
