package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CelLineapaquete generated by hbm2java
 */
@Entity
@Table(name = "cel_lineapaquete", catalog = "itaid")
public class CelLineapaquete implements java.io.Serializable {

	private CelLineapaqueteId id;

	public CelLineapaquete() {
	}

	public CelLineapaquete(CelLineapaqueteId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "celLineaId", column = @Column(name = "cel_linea_id", nullable = false)),
			@AttributeOverride(name = "celPaqueteId", column = @Column(name = "cel_paquete_id", nullable = false)) })
	public CelLineapaqueteId getId() {
		return this.id;
	}

	public void setId(CelLineapaqueteId id) {
		this.id = id;
	}

}
