package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CelLinea generated by hbm2java
 */
@Entity
@Table(name = "cel_linea", catalog = "itaid")
public class CelLinea implements java.io.Serializable {

	private int id;
	private String numero;
	private String cuenta;
	private String sim;
	private String ciudad;
	private int celPlanId;
	private Date planInicio;
	private int planPlazo;
	private int celAparatoId;
	private String asignatarioId;

	public CelLinea() {
	}

	public CelLinea(int id, String numero, String cuenta, String sim, String ciudad, int celPlanId, Date planInicio,
			int planPlazo, int celAparatoId) {
		this.id = id;
		this.numero = numero;
		this.cuenta = cuenta;
		this.sim = sim;
		this.ciudad = ciudad;
		this.celPlanId = celPlanId;
		this.planInicio = planInicio;
		this.planPlazo = planPlazo;
		this.celAparatoId = celAparatoId;
	}

	public CelLinea(int id, String numero, String cuenta, String sim, String ciudad, int celPlanId, Date planInicio,
			int planPlazo, int celAparatoId, String asignatarioId) {
		this.id = id;
		this.numero = numero;
		this.cuenta = cuenta;
		this.sim = sim;
		this.ciudad = ciudad;
		this.celPlanId = celPlanId;
		this.planInicio = planInicio;
		this.planPlazo = planPlazo;
		this.celAparatoId = celAparatoId;
		this.asignatarioId = asignatarioId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "numero", nullable = false, length = 10)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "cuenta", nullable = false, length = 8)
	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	@Column(name = "sim", nullable = false, length = 19)
	public String getSim() {
		return this.sim;
	}

	public void setSim(String sim) {
		this.sim = sim;
	}

	@Column(name = "ciudad", nullable = false, length = 15)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "cel_plan_id", nullable = false)
	public int getCelPlanId() {
		return this.celPlanId;
	}

	public void setCelPlanId(int celPlanId) {
		this.celPlanId = celPlanId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "plan_inicio", nullable = false, length = 10)
	public Date getPlanInicio() {
		return this.planInicio;
	}

	public void setPlanInicio(Date planInicio) {
		this.planInicio = planInicio;
	}

	@Column(name = "plan_plazo", nullable = false)
	public int getPlanPlazo() {
		return this.planPlazo;
	}

	public void setPlanPlazo(int planPlazo) {
		this.planPlazo = planPlazo;
	}

	@Column(name = "cel_aparato_id", nullable = false)
	public int getCelAparatoId() {
		return this.celAparatoId;
	}

	public void setCelAparatoId(int celAparatoId) {
		this.celAparatoId = celAparatoId;
	}

	@Column(name = "asignatario_id", length = 5)
	public String getAsignatarioId() {
		return this.asignatarioId;
	}

	public void setAsignatarioId(String asignatarioId) {
		this.asignatarioId = asignatarioId;
	}

}
