package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CelLineapaqueteId generated by hbm2java
 */
@Embeddable
public class CelLineapaqueteId implements java.io.Serializable {

	private int celLineaId;
	private int celPaqueteId;

	public CelLineapaqueteId() {
	}

	public CelLineapaqueteId(int celLineaId, int celPaqueteId) {
		this.celLineaId = celLineaId;
		this.celPaqueteId = celPaqueteId;
	}

	@Column(name = "cel_linea_id", nullable = false)
	public int getCelLineaId() {
		return this.celLineaId;
	}

	public void setCelLineaId(int celLineaId) {
		this.celLineaId = celLineaId;
	}

	@Column(name = "cel_paquete_id", nullable = false)
	public int getCelPaqueteId() {
		return this.celPaqueteId;
	}

	public void setCelPaqueteId(int celPaqueteId) {
		this.celPaqueteId = celPaqueteId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CelLineapaqueteId))
			return false;
		CelLineapaqueteId castOther = (CelLineapaqueteId) other;

		return (this.getCelLineaId() == castOther.getCelLineaId())
				&& (this.getCelPaqueteId() == castOther.getCelPaqueteId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCelLineaId();
		result = 37 * result + this.getCelPaqueteId();
		return result;
	}

}
