package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChecksoporteregionalId generated by hbm2java
 */
@Embeddable
public class ChecksoporteregionalId implements java.io.Serializable {

	private String servidor;
	private Date fecha;
	private String region;

	public ChecksoporteregionalId() {
	}

	public ChecksoporteregionalId(String servidor, Date fecha, String region) {
		this.servidor = servidor;
		this.fecha = fecha;
		this.region = region;
	}

	@Column(name = "servidor", nullable = false, length = 20)
	public String getServidor() {
		return this.servidor;
	}

	public void setServidor(String servidor) {
		this.servidor = servidor;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "region", nullable = false, length = 5)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChecksoporteregionalId))
			return false;
		ChecksoporteregionalId castOther = (ChecksoporteregionalId) other;

		return ((this.getServidor() == castOther.getServidor()) || (this.getServidor() != null
				&& castOther.getServidor() != null && this.getServidor().equals(castOther.getServidor())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getServidor() == null ? 0 : this.getServidor().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		return result;
	}

}
