package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DbSequence generated by hbm2java
 */
@Entity
@Table(name = "db_sequence", catalog = "itaid")
public class DbSequence implements java.io.Serializable {

	private String seqName;
	private int nextid;

	public DbSequence() {
	}

	public DbSequence(String seqName, int nextid) {
		this.seqName = seqName;
		this.nextid = nextid;
	}

	@Id

	@Column(name = "seq_name", unique = true, nullable = false, length = 100)
	public String getSeqName() {
		return this.seqName;
	}

	public void setSeqName(String seqName) {
		this.seqName = seqName;
	}

	@Column(name = "nextid", nullable = false)
	public int getNextid() {
		return this.nextid;
	}

	public void setNextid(int nextid) {
		this.nextid = nextid;
	}

}
