package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name = "distrito", catalog = "itaid")
public class Distrito implements java.io.Serializable {

	private int dclave;
	private String ddesc;
	private int zonaId;
	private int useq;

	public Distrito() {
	}

	public Distrito(int dclave, int zonaId, int useq) {
		this.dclave = dclave;
		this.zonaId = zonaId;
		this.useq = useq;
	}

	public Distrito(int dclave, String ddesc, int zonaId, int useq) {
		this.dclave = dclave;
		this.ddesc = ddesc;
		this.zonaId = zonaId;
		this.useq = useq;
	}

	@Id

	@Column(name = "dclave", unique = true, nullable = false)
	public int getDclave() {
		return this.dclave;
	}

	public void setDclave(int dclave) {
		this.dclave = dclave;
	}

	@Column(name = "ddesc", length = 100)
	public String getDdesc() {
		return this.ddesc;
	}

	public void setDdesc(String ddesc) {
		this.ddesc = ddesc;
	}

	@Column(name = "zona_id", nullable = false)
	public int getZonaId() {
		return this.zonaId;
	}

	public void setZonaId(int zonaId) {
		this.zonaId = zonaId;
	}

	@Column(name = "useq", nullable = false)
	public int getUseq() {
		return this.useq;
	}

	public void setUseq(int useq) {
		this.useq = useq;
	}

}
