package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EprojectEtapasStatus generated by hbm2java
 */
@Entity
@Table(name = "eproject_etapas_status", catalog = "itaid")
public class EprojectEtapasStatus implements java.io.Serializable {

	private EprojectEtapasStatusId id;

	public EprojectEtapasStatus() {
	}

	public EprojectEtapasStatus(EprojectEtapasStatusId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "snombre", column = @Column(name = "snombre", nullable = false, length = 65535)),
			@AttributeOverride(name = "sdescripcion", column = @Column(name = "sdescripcion", nullable = false, length = 65535)),
			@AttributeOverride(name = "sdescripcionCorta", column = @Column(name = "sdescripcion_corta", nullable = false, length = 10)),
			@AttributeOverride(name = "usercreate", column = @Column(name = "usercreate", nullable = false)),
			@AttributeOverride(name = "fechacreate", column = @Column(name = "fechacreate", nullable = false, length = 10)),
			@AttributeOverride(name = "usermod", column = @Column(name = "usermod")),
			@AttributeOverride(name = "fechamod", column = @Column(name = "fechamod", length = 10)),
			@AttributeOverride(name = "userdel", column = @Column(name = "userdel")),
			@AttributeOverride(name = "fechadel", column = @Column(name = "fechadel", length = 10)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false)),
			@AttributeOverride(name = "orden", column = @Column(name = "orden")) })
	public EprojectEtapasStatusId getId() {
		return this.id;
	}

	public void setId(EprojectEtapasStatusId id) {
		this.id = id;
	}

}
