package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EquipostockregionId generated by hbm2java
 */
@Embeddable
public class EquipostockregionId implements java.io.Serializable {

	private int equipo;
	private String tienda;
	private Date fecha;
	private String region;

	public EquipostockregionId() {
	}

	public EquipostockregionId(int equipo, String tienda, Date fecha, String region) {
		this.equipo = equipo;
		this.tienda = tienda;
		this.fecha = fecha;
		this.region = region;
	}

	@Column(name = "equipo", nullable = false)
	public int getEquipo() {
		return this.equipo;
	}

	public void setEquipo(int equipo) {
		this.equipo = equipo;
	}

	@Column(name = "tienda", nullable = false, length = 10)
	public String getTienda() {
		return this.tienda;
	}

	public void setTienda(String tienda) {
		this.tienda = tienda;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "region", nullable = false, length = 10)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EquipostockregionId))
			return false;
		EquipostockregionId castOther = (EquipostockregionId) other;

		return (this.getEquipo() == castOther.getEquipo())
				&& ((this.getTienda() == castOther.getTienda()) || (this.getTienda() != null
						&& castOther.getTienda() != null && this.getTienda().equals(castOther.getTienda())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEquipo();
		result = 37 * result + (getTienda() == null ? 0 : this.getTienda().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		return result;
	}

}
