package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GastosGasto generated by hbm2java
 */
@Entity
@Table(name = "gastos_gasto", catalog = "itaid")
public class GastosGasto implements java.io.Serializable {

	private int id;
	private int gastosReporteId;
	private Date fecha;
	private String detalle;
	private int gastosCategoriaId;
	private Integer numComprobante;
	private BigDecimal importe;
	private BigDecimal impuestos;
	private BigDecimal subtotal;
	private Integer gastosCuentacontId;

	public GastosGasto() {
	}

	public GastosGasto(int id, int gastosReporteId, Date fecha, String detalle, int gastosCategoriaId,
			BigDecimal subtotal) {
		this.id = id;
		this.gastosReporteId = gastosReporteId;
		this.fecha = fecha;
		this.detalle = detalle;
		this.gastosCategoriaId = gastosCategoriaId;
		this.subtotal = subtotal;
	}

	public GastosGasto(int id, int gastosReporteId, Date fecha, String detalle, int gastosCategoriaId,
			Integer numComprobante, BigDecimal importe, BigDecimal impuestos, BigDecimal subtotal,
			Integer gastosCuentacontId) {
		this.id = id;
		this.gastosReporteId = gastosReporteId;
		this.fecha = fecha;
		this.detalle = detalle;
		this.gastosCategoriaId = gastosCategoriaId;
		this.numComprobante = numComprobante;
		this.importe = importe;
		this.impuestos = impuestos;
		this.subtotal = subtotal;
		this.gastosCuentacontId = gastosCuentacontId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "gastos_reporte_id", nullable = false)
	public int getGastosReporteId() {
		return this.gastosReporteId;
	}

	public void setGastosReporteId(int gastosReporteId) {
		this.gastosReporteId = gastosReporteId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "detalle", nullable = false)
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "gastos_categoria_id", nullable = false)
	public int getGastosCategoriaId() {
		return this.gastosCategoriaId;
	}

	public void setGastosCategoriaId(int gastosCategoriaId) {
		this.gastosCategoriaId = gastosCategoriaId;
	}

	@Column(name = "num_comprobante")
	public Integer getNumComprobante() {
		return this.numComprobante;
	}

	public void setNumComprobante(Integer numComprobante) {
		this.numComprobante = numComprobante;
	}

	@Column(name = "importe", precision = 7)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "impuestos", precision = 7)
	public BigDecimal getImpuestos() {
		return this.impuestos;
	}

	public void setImpuestos(BigDecimal impuestos) {
		this.impuestos = impuestos;
	}

	@Column(name = "subtotal", nullable = false, precision = 7)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "gastos_cuentacont_id")
	public Integer getGastosCuentacontId() {
		return this.gastosCuentacontId;
	}

	public void setGastosCuentacontId(Integer gastosCuentacontId) {
		this.gastosCuentacontId = gastosCuentacontId;
	}

}
