package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GastosCategoria generated by hbm2java
 */
@Entity
@Table(name = "gastos_categoria", catalog = "itaid")
public class GastosCategoria implements java.io.Serializable {

	private int id;
	private String nombre;
	private String observacion;
	private Integer region;
	private Boolean suma;
	private boolean status;

	public GastosCategoria() {
	}

	public GastosCategoria(int id, String nombre, boolean status) {
		this.id = id;
		this.nombre = nombre;
		this.status = status;
	}

	public GastosCategoria(int id, String nombre, String observacion, Integer region, Boolean suma, boolean status) {
		this.id = id;
		this.nombre = nombre;
		this.observacion = observacion;
		this.region = region;
		this.suma = suma;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "region")
	public Integer getRegion() {
		return this.region;
	}

	public void setRegion(Integer region) {
		this.region = region;
	}

	@Column(name = "suma")
	public Boolean getSuma() {
		return this.suma;
	}

	public void setSuma(Boolean suma) {
		this.suma = suma;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
