package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logtickets generated by hbm2java
 */
@Entity
@Table(name = "logtickets", catalog = "itaid")
public class Logtickets implements java.io.Serializable {

	private Integer id;
	private int ticket;
	private int estatusanterior;
	private int estatusnuevo;
	private String descripcion;
	private Date fechacambio;
	private int tecnicoid;

	public Logtickets() {
	}

	public Logtickets(int ticket, int estatusanterior, int estatusnuevo, String descripcion, Date fechacambio,
			int tecnicoid) {
		this.ticket = ticket;
		this.estatusanterior = estatusanterior;
		this.estatusnuevo = estatusnuevo;
		this.descripcion = descripcion;
		this.fechacambio = fechacambio;
		this.tecnicoid = tecnicoid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ticket", nullable = false)
	public int getTicket() {
		return this.ticket;
	}

	public void setTicket(int ticket) {
		this.ticket = ticket;
	}

	@Column(name = "estatusanterior", nullable = false)
	public int getEstatusanterior() {
		return this.estatusanterior;
	}

	public void setEstatusanterior(int estatusanterior) {
		this.estatusanterior = estatusanterior;
	}

	@Column(name = "estatusnuevo", nullable = false)
	public int getEstatusnuevo() {
		return this.estatusnuevo;
	}

	public void setEstatusnuevo(int estatusnuevo) {
		this.estatusnuevo = estatusnuevo;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacambio", nullable = false, length = 10)
	public Date getFechacambio() {
		return this.fechacambio;
	}

	public void setFechacambio(Date fechacambio) {
		this.fechacambio = fechacambio;
	}

	@Column(name = "tecnicoid", nullable = false)
	public int getTecnicoid() {
		return this.tecnicoid;
	}

	public void setTecnicoid(int tecnicoid) {
		this.tecnicoid = tecnicoid;
	}

}
