package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PbcatedtId generated by hbm2java
 */
@Embeddable
public class PbcatedtId implements java.io.Serializable {

	private String pbeName;
	private String pbeEdit;
	private Short pbeType;
	private Integer pbeCntr;
	private short pbeSeqn;
	private Integer pbeFlag;
	private String pbeWork;

	public PbcatedtId() {
	}

	public PbcatedtId(String pbeName, short pbeSeqn) {
		this.pbeName = pbeName;
		this.pbeSeqn = pbeSeqn;
	}

	public PbcatedtId(String pbeName, String pbeEdit, Short pbeType, Integer pbeCntr, short pbeSeqn, Integer pbeFlag,
			String pbeWork) {
		this.pbeName = pbeName;
		this.pbeEdit = pbeEdit;
		this.pbeType = pbeType;
		this.pbeCntr = pbeCntr;
		this.pbeSeqn = pbeSeqn;
		this.pbeFlag = pbeFlag;
		this.pbeWork = pbeWork;
	}

	@Column(name = "pbe_name", nullable = false, length = 30)
	public String getPbeName() {
		return this.pbeName;
	}

	public void setPbeName(String pbeName) {
		this.pbeName = pbeName;
	}

	@Column(name = "pbe_edit", length = 254)
	public String getPbeEdit() {
		return this.pbeEdit;
	}

	public void setPbeEdit(String pbeEdit) {
		this.pbeEdit = pbeEdit;
	}

	@Column(name = "pbe_type")
	public Short getPbeType() {
		return this.pbeType;
	}

	public void setPbeType(Short pbeType) {
		this.pbeType = pbeType;
	}

	@Column(name = "pbe_cntr")
	public Integer getPbeCntr() {
		return this.pbeCntr;
	}

	public void setPbeCntr(Integer pbeCntr) {
		this.pbeCntr = pbeCntr;
	}

	@Column(name = "pbe_seqn", nullable = false)
	public short getPbeSeqn() {
		return this.pbeSeqn;
	}

	public void setPbeSeqn(short pbeSeqn) {
		this.pbeSeqn = pbeSeqn;
	}

	@Column(name = "pbe_flag")
	public Integer getPbeFlag() {
		return this.pbeFlag;
	}

	public void setPbeFlag(Integer pbeFlag) {
		this.pbeFlag = pbeFlag;
	}

	@Column(name = "pbe_work", length = 32)
	public String getPbeWork() {
		return this.pbeWork;
	}

	public void setPbeWork(String pbeWork) {
		this.pbeWork = pbeWork;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PbcatedtId))
			return false;
		PbcatedtId castOther = (PbcatedtId) other;

		return ((this.getPbeName() == castOther.getPbeName()) || (this.getPbeName() != null
				&& castOther.getPbeName() != null && this.getPbeName().equals(castOther.getPbeName())))
				&& ((this.getPbeEdit() == castOther.getPbeEdit()) || (this.getPbeEdit() != null
						&& castOther.getPbeEdit() != null && this.getPbeEdit().equals(castOther.getPbeEdit())))
				&& ((this.getPbeType() == castOther.getPbeType()) || (this.getPbeType() != null
						&& castOther.getPbeType() != null && this.getPbeType().equals(castOther.getPbeType())))
				&& ((this.getPbeCntr() == castOther.getPbeCntr()) || (this.getPbeCntr() != null
						&& castOther.getPbeCntr() != null && this.getPbeCntr().equals(castOther.getPbeCntr())))
				&& (this.getPbeSeqn() == castOther.getPbeSeqn())
				&& ((this.getPbeFlag() == castOther.getPbeFlag()) || (this.getPbeFlag() != null
						&& castOther.getPbeFlag() != null && this.getPbeFlag().equals(castOther.getPbeFlag())))
				&& ((this.getPbeWork() == castOther.getPbeWork()) || (this.getPbeWork() != null
						&& castOther.getPbeWork() != null && this.getPbeWork().equals(castOther.getPbeWork())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPbeName() == null ? 0 : this.getPbeName().hashCode());
		result = 37 * result + (getPbeEdit() == null ? 0 : this.getPbeEdit().hashCode());
		result = 37 * result + (getPbeType() == null ? 0 : this.getPbeType().hashCode());
		result = 37 * result + (getPbeCntr() == null ? 0 : this.getPbeCntr().hashCode());
		result = 37 * result + this.getPbeSeqn();
		result = 37 * result + (getPbeFlag() == null ? 0 : this.getPbeFlag().hashCode());
		result = 37 * result + (getPbeWork() == null ? 0 : this.getPbeWork().hashCode());
		return result;
	}

}
