package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pbcatedt generated by hbm2java
 */
@Entity
@Table(name = "pbcatedt", catalog = "itaid", uniqueConstraints = @UniqueConstraint(columnNames = { "pbe_name",
		"pbe_seqn" }))
public class Pbcatedt implements java.io.Serializable {

	private PbcatedtId id;

	public Pbcatedt() {
	}

	public Pbcatedt(PbcatedtId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pbeName", column = @Column(name = "pbe_name", nullable = false, length = 30)),
			@AttributeOverride(name = "pbeEdit", column = @Column(name = "pbe_edit", length = 254)),
			@AttributeOverride(name = "pbeType", column = @Column(name = "pbe_type")),
			@AttributeOverride(name = "pbeCntr", column = @Column(name = "pbe_cntr")),
			@AttributeOverride(name = "pbeSeqn", column = @Column(name = "pbe_seqn", nullable = false)),
			@AttributeOverride(name = "pbeFlag", column = @Column(name = "pbe_flag")),
			@AttributeOverride(name = "pbeWork", column = @Column(name = "pbe_work", length = 32)) })
	public PbcatedtId getId() {
		return this.id;
	}

	public void setId(PbcatedtId id) {
		this.id = id;
	}

}
