package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfileSolicitudAm generated by hbm2java
 */
@Entity
@Table(name = "profile_solicitud_am", catalog = "itaid")
public class ProfileSolicitudAm implements java.io.Serializable {

	private Integer id;
	private int profileId;
	private int activomodeloId;
	private double costo;
	private int userCreate;
	private Date dateCreate;
	private boolean status;

	public ProfileSolicitudAm() {
	}

	public ProfileSolicitudAm(int profileId, int activomodeloId, double costo, int userCreate, Date dateCreate,
			boolean status) {
		this.profileId = profileId;
		this.activomodeloId = activomodeloId;
		this.costo = costo;
		this.userCreate = userCreate;
		this.dateCreate = dateCreate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "profile_id", nullable = false)
	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	@Column(name = "activomodelo_id", nullable = false)
	public int getActivomodeloId() {
		return this.activomodeloId;
	}

	public void setActivomodeloId(int activomodeloId) {
		this.activomodeloId = activomodeloId;
	}

	@Column(name = "costo", nullable = false, precision = 22, scale = 0)
	public double getCosto() {
		return this.costo;
	}

	public void setCosto(double costo) {
		this.costo = costo;
	}

	@Column(name = "user_create", nullable = false)
	public int getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(int userCreate) {
		this.userCreate = userCreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_create", nullable = false, length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
