package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", catalog = "itaid")
public class Proveedor implements java.io.Serializable {

	private Integer id;
	private String razonsocial;
	private String descripcion;
	private String rfc;
	private String calle;
	private String numerocalle;
	private String colonia;
	private String municipio;
	private String ciudad;
	private String codigopostal;
	private String telefono1;
	private String extension1;
	private String telefono2;
	private String extension2;
	private String cont1;
	private String telefonocont1;
	private String emailcont1;
	private String cont2;
	private String telefonocont2;
	private String emailcont2;
	private String cuenta;
	private Integer diasEntrega;
	private Integer diasPago;
	private Integer status;
	private String clave;
	private String contrato;
	private String acta;
	private String identificacion;

	public Proveedor() {
	}

	public Proveedor(String razonsocial, String rfc, String ciudad, String telefono2, String cont1,
			String telefonocont1, String emailcont2, String cuenta) {
		this.razonsocial = razonsocial;
		this.rfc = rfc;
		this.ciudad = ciudad;
		this.telefono2 = telefono2;
		this.cont1 = cont1;
		this.telefonocont1 = telefonocont1;
		this.emailcont2 = emailcont2;
		this.cuenta = cuenta;
	}

	public Proveedor(String razonsocial, String descripcion, String rfc, String calle, String numerocalle,
			String colonia, String municipio, String ciudad, String codigopostal, String telefono1, String extension1,
			String telefono2, String extension2, String cont1, String telefonocont1, String emailcont1, String cont2,
			String telefonocont2, String emailcont2, String cuenta, Integer diasEntrega, Integer diasPago,
			Integer status, String clave, String contrato, String acta, String identificacion) {
		this.razonsocial = razonsocial;
		this.descripcion = descripcion;
		this.rfc = rfc;
		this.calle = calle;
		this.numerocalle = numerocalle;
		this.colonia = colonia;
		this.municipio = municipio;
		this.ciudad = ciudad;
		this.codigopostal = codigopostal;
		this.telefono1 = telefono1;
		this.extension1 = extension1;
		this.telefono2 = telefono2;
		this.extension2 = extension2;
		this.cont1 = cont1;
		this.telefonocont1 = telefonocont1;
		this.emailcont1 = emailcont1;
		this.cont2 = cont2;
		this.telefonocont2 = telefonocont2;
		this.emailcont2 = emailcont2;
		this.cuenta = cuenta;
		this.diasEntrega = diasEntrega;
		this.diasPago = diasPago;
		this.status = status;
		this.clave = clave;
		this.contrato = contrato;
		this.acta = acta;
		this.identificacion = identificacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "razonsocial", nullable = false)
	public String getRazonsocial() {
		return this.razonsocial;
	}

	public void setRazonsocial(String razonsocial) {
		this.razonsocial = razonsocial;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "rfc", nullable = false, length = 13)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "calle", length = 30)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "numerocalle", length = 10)
	public String getNumerocalle() {
		return this.numerocalle;
	}

	public void setNumerocalle(String numerocalle) {
		this.numerocalle = numerocalle;
	}

	@Column(name = "colonia", length = 25)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "municipio", length = 25)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "ciudad", nullable = false, length = 25)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "codigopostal", length = 6)
	public String getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(String codigopostal) {
		this.codigopostal = codigopostal;
	}

	@Column(name = "telefono1", length = 10)
	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	@Column(name = "extension1", length = 5)
	public String getExtension1() {
		return this.extension1;
	}

	public void setExtension1(String extension1) {
		this.extension1 = extension1;
	}

	@Column(name = "telefono2", nullable = false, length = 10)
	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	@Column(name = "extension2", length = 5)
	public String getExtension2() {
		return this.extension2;
	}

	public void setExtension2(String extension2) {
		this.extension2 = extension2;
	}

	@Column(name = "cont1", nullable = false, length = 50)
	public String getCont1() {
		return this.cont1;
	}

	public void setCont1(String cont1) {
		this.cont1 = cont1;
	}

	@Column(name = "telefonocont1", nullable = false, length = 10)
	public String getTelefonocont1() {
		return this.telefonocont1;
	}

	public void setTelefonocont1(String telefonocont1) {
		this.telefonocont1 = telefonocont1;
	}

	@Column(name = "emailcont1", length = 45)
	public String getEmailcont1() {
		return this.emailcont1;
	}

	public void setEmailcont1(String emailcont1) {
		this.emailcont1 = emailcont1;
	}

	@Column(name = "cont2", length = 50)
	public String getCont2() {
		return this.cont2;
	}

	public void setCont2(String cont2) {
		this.cont2 = cont2;
	}

	@Column(name = "telefonocont2", length = 10)
	public String getTelefonocont2() {
		return this.telefonocont2;
	}

	public void setTelefonocont2(String telefonocont2) {
		this.telefonocont2 = telefonocont2;
	}

	@Column(name = "emailcont2", nullable = false, length = 45)
	public String getEmailcont2() {
		return this.emailcont2;
	}

	public void setEmailcont2(String emailcont2) {
		this.emailcont2 = emailcont2;
	}

	@Column(name = "cuenta", nullable = false, length = 65535)
	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	@Column(name = "dias_entrega")
	public Integer getDiasEntrega() {
		return this.diasEntrega;
	}

	public void setDiasEntrega(Integer diasEntrega) {
		this.diasEntrega = diasEntrega;
	}

	@Column(name = "dias_pago")
	public Integer getDiasPago() {
		return this.diasPago;
	}

	public void setDiasPago(Integer diasPago) {
		this.diasPago = diasPago;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "clave", length = 4)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "contrato")
	public String getContrato() {
		return this.contrato;
	}

	public void setContrato(String contrato) {
		this.contrato = contrato;
	}

	@Column(name = "acta")
	public String getActa() {
		return this.acta;
	}

	public void setActa(String acta) {
		this.acta = acta;
	}

	@Column(name = "identificacion")
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

}
