package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Proyectorep generated by hbm2java
 */
@Entity
@Table(name = "proyectorep", catalog = "itaid")
public class Proyectorep implements java.io.Serializable {

	private ProyectorepId id;

	public Proyectorep() {
	}

	public Proyectorep(ProyectorepId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "proyecto", column = @Column(name = "proyecto", nullable = false, length = 30)),
			@AttributeOverride(name = "fase", column = @Column(name = "fase", nullable = false, length = 30)),
			@AttributeOverride(name = "tarea", column = @Column(name = "tarea", nullable = false, length = 50)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "descripcion", nullable = false)),
			@AttributeOverride(name = "entregable", column = @Column(name = "entregable", length = 35)),
			@AttributeOverride(name = "prioridad", column = @Column(name = "prioridad", nullable = false, length = 5)),
			@AttributeOverride(name = "fechafinact", column = @Column(name = "fechafinact", nullable = false, length = 10)),
			@AttributeOverride(name = "avance", column = @Column(name = "avance", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "observaciones", column = @Column(name = "observaciones")),
			@AttributeOverride(name = "categoria", column = @Column(name = "categoria", length = 10)),
			@AttributeOverride(name = "estado", column = @Column(name = "estado", nullable = false, length = 20)),
			@AttributeOverride(name = "tecnico", column = @Column(name = "tecnico", length = 51)) })
	public ProyectorepId getId() {
		return this.id;
	}

	public void setId(ProyectorepId id) {
		this.id = id;
	}

}
