package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto", catalog = "itaid")
public class Proyecto implements java.io.Serializable {

	private int id;
	private String nombre;
	private int proyectocategoriaId;
	private Integer solicitanteId;
	private byte cerrado;

	public Proyecto() {
	}

	public Proyecto(int id, String nombre, int proyectocategoriaId, byte cerrado) {
		this.id = id;
		this.nombre = nombre;
		this.proyectocategoriaId = proyectocategoriaId;
		this.cerrado = cerrado;
	}

	public Proyecto(int id, String nombre, int proyectocategoriaId, Integer solicitanteId, byte cerrado) {
		this.id = id;
		this.nombre = nombre;
		this.proyectocategoriaId = proyectocategoriaId;
		this.solicitanteId = solicitanteId;
		this.cerrado = cerrado;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "proyectocategoria_id", nullable = false)
	public int getProyectocategoriaId() {
		return this.proyectocategoriaId;
	}

	public void setProyectocategoriaId(int proyectocategoriaId) {
		this.proyectocategoriaId = proyectocategoriaId;
	}

	@Column(name = "solicitante_id")
	public Integer getSolicitanteId() {
		return this.solicitanteId;
	}

	public void setSolicitanteId(Integer solicitanteId) {
		this.solicitanteId = solicitanteId;
	}

	@Column(name = "cerrado", nullable = false)
	public byte getCerrado() {
		return this.cerrado;
	}

	public void setCerrado(byte cerrado) {
		this.cerrado = cerrado;
	}

}
