package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "itaid")
public class Region implements java.io.Serializable {

	private int rclave;
	private String rdesc;
	private int useq;

	public Region() {
	}

	public Region(int rclave, String rdesc, int useq) {
		this.rclave = rclave;
		this.rdesc = rdesc;
		this.useq = useq;
	}

	@Id

	@Column(name = "rclave", unique = true, nullable = false)
	public int getRclave() {
		return this.rclave;
	}

	public void setRclave(int rclave) {
		this.rclave = rclave;
	}

	@Column(name = "rdesc", nullable = false, length = 50)
	public String getRdesc() {
		return this.rdesc;
	}

	public void setRdesc(String rdesc) {
		this.rdesc = rdesc;
	}

	@Column(name = "useq", nullable = false)
	public int getUseq() {
		return this.useq;
	}

	public void setUseq(int useq) {
		this.useq = useq;
	}

}
