package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RegionRentas generated by hbm2java
 */
@Entity
@Table(name = "region_rentas", catalog = "itaid")
public class RegionRentas implements java.io.Serializable {

	private int id;
	private String nombre;
	private int estadoRentasId;

	public RegionRentas() {
	}

	public RegionRentas(int id, String nombre, int estadoRentasId) {
		this.id = id;
		this.nombre = nombre;
		this.estadoRentasId = estadoRentasId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado_rentas_id", nullable = false)
	public int getEstadoRentasId() {
		return this.estadoRentasId;
	}

	public void setEstadoRentasId(int estadoRentasId) {
		this.estadoRentasId = estadoRentasId;
	}

}
