package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServidoresValidacionRespaldo generated by hbm2java
 */
@Entity
@Table(name = "servidores_validacion_respaldo", catalog = "itaid")
public class ServidoresValidacionRespaldo implements java.io.Serializable {

	private Integer id;
	private Date fechaVerificacion;
	private int servidorId;
	private Date fechaRespaldo;
	private byte ejecucionRespaldo;
	private String observaciones;
	private int usercreate;
	private Date fechacreate;
	private int usermod;
	private Date fechamod;
	private int userdel;
	private Date fechadel;
	private byte status;

	public ServidoresValidacionRespaldo() {
	}

	public ServidoresValidacionRespaldo(Date fechaVerificacion, int servidorId, Date fechaRespaldo,
			byte ejecucionRespaldo, String observaciones, int usercreate, Date fechacreate, int usermod, Date fechamod,
			int userdel, Date fechadel, byte status) {
		this.fechaVerificacion = fechaVerificacion;
		this.servidorId = servidorId;
		this.fechaRespaldo = fechaRespaldo;
		this.ejecucionRespaldo = ejecucionRespaldo;
		this.observaciones = observaciones;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.usermod = usermod;
		this.fechamod = fechamod;
		this.userdel = userdel;
		this.fechadel = fechadel;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_verificacion", nullable = false, length = 10)
	public Date getFechaVerificacion() {
		return this.fechaVerificacion;
	}

	public void setFechaVerificacion(Date fechaVerificacion) {
		this.fechaVerificacion = fechaVerificacion;
	}

	@Column(name = "servidor_id", nullable = false)
	public int getServidorId() {
		return this.servidorId;
	}

	public void setServidorId(int servidorId) {
		this.servidorId = servidorId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_respaldo", nullable = false, length = 10)
	public Date getFechaRespaldo() {
		return this.fechaRespaldo;
	}

	public void setFechaRespaldo(Date fechaRespaldo) {
		this.fechaRespaldo = fechaRespaldo;
	}

	@Column(name = "ejecucion_respaldo", nullable = false)
	public byte getEjecucionRespaldo() {
		return this.ejecucionRespaldo;
	}

	public void setEjecucionRespaldo(byte ejecucionRespaldo) {
		this.ejecucionRespaldo = ejecucionRespaldo;
	}

	@Column(name = "observaciones", nullable = false, length = 65535)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacreate", nullable = false, length = 19)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "usermod", nullable = false)
	public int getUsermod() {
		return this.usermod;
	}

	public void setUsermod(int usermod) {
		this.usermod = usermod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamod", nullable = false, length = 19)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "userdel", nullable = false)
	public int getUserdel() {
		return this.userdel;
	}

	public void setUserdel(int userdel) {
		this.userdel = userdel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechadel", nullable = false, length = 19)
	public Date getFechadel() {
		return this.fechadel;
	}

	public void setFechadel(Date fechadel) {
		this.fechadel = fechadel;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
