package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServidoresEnvio generated by hbm2java
 */
@Entity
@Table(name = "servidores_envio", catalog = "itaid")
public class ServidoresEnvio implements java.io.Serializable {

	private Integer id;
	private String tipo;
	private Date fecha;
	private int usercreate;
	private Date fechacreate;
	private int usermod;
	private Date fechamod;
	private byte status;

	public ServidoresEnvio() {
	}

	public ServidoresEnvio(String tipo, Date fecha, int usercreate, Date fechacreate, int usermod, Date fechamod,
			byte status) {
		this.tipo = tipo;
		this.fecha = fecha;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.usermod = usermod;
		this.fechamod = fechamod;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tipo", nullable = false)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacreate", nullable = false, length = 19)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "usermod", nullable = false)
	public int getUsermod() {
		return this.usermod;
	}

	public void setUsermod(int usermod) {
		this.usermod = usermod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamod", nullable = false, length = 19)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
