package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SintomaDiagnostico generated by hbm2java
 */
@Entity
@Table(name = "sintoma_diagnostico", catalog = "itaid")
public class SintomaDiagnostico implements java.io.Serializable {

	private Integer id;
	private String diagnostico;
	private String sub;
	private int sintomaId;
	private int diagnosticoId;
	private byte disminuir;
	private boolean status;
	private boolean renueva;

	public SintomaDiagnostico() {
	}

	public SintomaDiagnostico(String diagnostico, String sub, int sintomaId, int diagnosticoId, byte disminuir,
			boolean status, boolean renueva) {
		this.diagnostico = diagnostico;
		this.sub = sub;
		this.sintomaId = sintomaId;
		this.diagnosticoId = diagnosticoId;
		this.disminuir = disminuir;
		this.status = status;
		this.renueva = renueva;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "diagnostico", nullable = false)
	public String getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	@Column(name = "sub", nullable = false)
	public String getSub() {
		return this.sub;
	}

	public void setSub(String sub) {
		this.sub = sub;
	}

	@Column(name = "sintoma_id", nullable = false)
	public int getSintomaId() {
		return this.sintomaId;
	}

	public void setSintomaId(int sintomaId) {
		this.sintomaId = sintomaId;
	}

	@Column(name = "diagnostico_id", nullable = false)
	public int getDiagnosticoId() {
		return this.diagnosticoId;
	}

	public void setDiagnosticoId(int diagnosticoId) {
		this.diagnosticoId = diagnosticoId;
	}

	@Column(name = "disminuir", nullable = false)
	public byte getDisminuir() {
		return this.disminuir;
	}

	public void setDisminuir(byte disminuir) {
		this.disminuir = disminuir;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "renueva", nullable = false)
	public boolean isRenueva() {
		return this.renueva;
	}

	public void setRenueva(boolean renueva) {
		this.renueva = renueva;
	}

}
