package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sintoma generated by hbm2java
 */
@Entity
@Table(name = "sintoma", catalog = "itaid")
public class Sintoma implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String sub;
	private String descripcion;
	private byte fallo;
	private String status;

	public Sintoma() {
	}

	public Sintoma(String nombre, byte fallo, String status) {
		this.nombre = nombre;
		this.fallo = fallo;
		this.status = status;
	}

	public Sintoma(String nombre, String sub, String descripcion, byte fallo, String status) {
		this.nombre = nombre;
		this.sub = sub;
		this.descripcion = descripcion;
		this.fallo = fallo;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 70)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "sub")
	public String getSub() {
		return this.sub;
	}

	public void setSub(String sub) {
		this.sub = sub;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "fallo", nullable = false)
	public byte getFallo() {
		return this.fallo;
	}

	public void setFallo(byte fallo) {
		this.fallo = fallo;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
