package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "sucursal", catalog = "itaid")
public class Sucursal implements java.io.Serializable {

	private Integer id;
	private String numero3b;
	private String nombre;
	private String calle;
	private String numerocalle;
	private String colonia;
	private String municipio;
	private String ciudad;
	private String codigopostal;
	private String telefonofijo;
	private String telefonocelular;
	private int tiposucursalId;
	private Integer almacenId;
	private Integer distritoId;
	private int tecnicoId;
	private Integer status;
	private Integer encargadoId;
	private Boolean entregaCompra;
	private String clave;
	private String emails;
	private byte region;
	private Date fechacreate;
	private int usercreate;
	private Integer usermod;
	private Date fechamod;
	private Integer userdel;
	private Date fechadel;

	public Sucursal() {
	}

	public Sucursal(String numero3b, String nombre, String ciudad, int tiposucursalId, int tecnicoId, byte region,
			Date fechacreate, int usercreate) {
		this.numero3b = numero3b;
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.tiposucursalId = tiposucursalId;
		this.tecnicoId = tecnicoId;
		this.region = region;
		this.fechacreate = fechacreate;
		this.usercreate = usercreate;
	}

	public Sucursal(String numero3b, String nombre, String calle, String numerocalle, String colonia, String municipio,
			String ciudad, String codigopostal, String telefonofijo, String telefonocelular, int tiposucursalId,
			Integer almacenId, Integer distritoId, int tecnicoId, Integer status, Integer encargadoId,
			Boolean entregaCompra, String clave, String emails, byte region, Date fechacreate, int usercreate,
			Integer usermod, Date fechamod, Integer userdel, Date fechadel) {
		this.numero3b = numero3b;
		this.nombre = nombre;
		this.calle = calle;
		this.numerocalle = numerocalle;
		this.colonia = colonia;
		this.municipio = municipio;
		this.ciudad = ciudad;
		this.codigopostal = codigopostal;
		this.telefonofijo = telefonofijo;
		this.telefonocelular = telefonocelular;
		this.tiposucursalId = tiposucursalId;
		this.almacenId = almacenId;
		this.distritoId = distritoId;
		this.tecnicoId = tecnicoId;
		this.status = status;
		this.encargadoId = encargadoId;
		this.entregaCompra = entregaCompra;
		this.clave = clave;
		this.emails = emails;
		this.region = region;
		this.fechacreate = fechacreate;
		this.usercreate = usercreate;
		this.usermod = usermod;
		this.fechamod = fechamod;
		this.userdel = userdel;
		this.fechadel = fechadel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "numero3b", nullable = false, length = 4)
	public String getNumero3b() {
		return this.numero3b;
	}

	public void setNumero3b(String numero3b) {
		this.numero3b = numero3b;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "calle", length = 25)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "numerocalle", length = 10)
	public String getNumerocalle() {
		return this.numerocalle;
	}

	public void setNumerocalle(String numerocalle) {
		this.numerocalle = numerocalle;
	}

	@Column(name = "colonia", length = 25)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "municipio", length = 25)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "ciudad", nullable = false, length = 25)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "codigopostal", length = 6)
	public String getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(String codigopostal) {
		this.codigopostal = codigopostal;
	}

	@Column(name = "telefonofijo", length = 10)
	public String getTelefonofijo() {
		return this.telefonofijo;
	}

	public void setTelefonofijo(String telefonofijo) {
		this.telefonofijo = telefonofijo;
	}

	@Column(name = "telefonocelular", length = 10)
	public String getTelefonocelular() {
		return this.telefonocelular;
	}

	public void setTelefonocelular(String telefonocelular) {
		this.telefonocelular = telefonocelular;
	}

	@Column(name = "tiposucursal_id", nullable = false)
	public int getTiposucursalId() {
		return this.tiposucursalId;
	}

	public void setTiposucursalId(int tiposucursalId) {
		this.tiposucursalId = tiposucursalId;
	}

	@Column(name = "almacen_id")
	public Integer getAlmacenId() {
		return this.almacenId;
	}

	public void setAlmacenId(Integer almacenId) {
		this.almacenId = almacenId;
	}

	@Column(name = "distrito_id")
	public Integer getDistritoId() {
		return this.distritoId;
	}

	public void setDistritoId(Integer distritoId) {
		this.distritoId = distritoId;
	}

	@Column(name = "tecnico_id", nullable = false)
	public int getTecnicoId() {
		return this.tecnicoId;
	}

	public void setTecnicoId(int tecnicoId) {
		this.tecnicoId = tecnicoId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "encargado_id")
	public Integer getEncargadoId() {
		return this.encargadoId;
	}

	public void setEncargadoId(Integer encargadoId) {
		this.encargadoId = encargadoId;
	}

	@Column(name = "entrega_compra")
	public Boolean getEntregaCompra() {
		return this.entregaCompra;
	}

	public void setEntregaCompra(Boolean entregaCompra) {
		this.entregaCompra = entregaCompra;
	}

	@Column(name = "clave", length = 4)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "emails", length = 65535)
	public String getEmails() {
		return this.emails;
	}

	public void setEmails(String emails) {
		this.emails = emails;
	}

	@Column(name = "region", nullable = false)
	public byte getRegion() {
		return this.region;
	}

	public void setRegion(byte region) {
		this.region = region;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacreate", nullable = false, length = 19)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Column(name = "usermod")
	public Integer getUsermod() {
		return this.usermod;
	}

	public void setUsermod(Integer usermod) {
		this.usermod = usermod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamod", length = 19)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "userdel")
	public Integer getUserdel() {
		return this.userdel;
	}

	public void setUserdel(Integer userdel) {
		this.userdel = userdel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechadel", length = 19)
	public Date getFechadel() {
		return this.fechadel;
	}

	public void setFechadel(Date fechadel) {
		this.fechadel = fechadel;
	}

}
