package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TareaEstado generated by hbm2java
 */
@Entity
@Table(name = "tarea_estado", catalog = "itaid")
public class TareaEstado implements java.io.Serializable {

	private int id;
	private String nombre;

	public TareaEstado() {
	}

	public TareaEstado(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
