package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tienda generated by hbm2java
 */
@Entity
@Table(name = "tienda", catalog = "itaid")
public class Tienda implements java.io.Serializable {

	private int tclave;
	private String tnombre;
	private int dclave;
	private String talmacen;

	public Tienda() {
	}

	public Tienda(int tclave, String tnombre, int dclave, String talmacen) {
		this.tclave = tclave;
		this.tnombre = tnombre;
		this.dclave = dclave;
		this.talmacen = talmacen;
	}

	@Id

	@Column(name = "tclave", unique = true, nullable = false)
	public int getTclave() {
		return this.tclave;
	}

	public void setTclave(int tclave) {
		this.tclave = tclave;
	}

	@Column(name = "tnombre", nullable = false, length = 20)
	public String getTnombre() {
		return this.tnombre;
	}

	public void setTnombre(String tnombre) {
		this.tnombre = tnombre;
	}

	@Column(name = "dclave", nullable = false)
	public int getDclave() {
		return this.dclave;
	}

	public void setDclave(int dclave) {
		this.dclave = dclave;
	}

	@Column(name = "talmacen", nullable = false, length = 5)
	public String getTalmacen() {
		return this.talmacen;
	}

	public void setTalmacen(String talmacen) {
		this.talmacen = talmacen;
	}

}
