package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoMoneda generated by hbm2java
 */
@Entity
@Table(name = "tipo_moneda", catalog = "itaid")
public class TipoMoneda implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private float tipoCambio;
	private String acronimo;
	private boolean status;

	public TipoMoneda() {
	}

	public TipoMoneda(String nombre, float tipoCambio, boolean status) {
		this.nombre = nombre;
		this.tipoCambio = tipoCambio;
		this.status = status;
	}

	public TipoMoneda(String nombre, float tipoCambio, String acronimo, boolean status) {
		this.nombre = nombre;
		this.tipoCambio = tipoCambio;
		this.acronimo = acronimo;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 12)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo_cambio", nullable = false, precision = 12, scale = 0)
	public float getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(float tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	@Column(name = "acronimo", length = 10)
	public String getAcronimo() {
		return this.acronimo;
	}

	public void setAcronimo(String acronimo) {
		this.acronimo = acronimo;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
