package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:17:38 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VacacionesAnt generated by hbm2java
 */
@Entity
@Table(name = "vacaciones_ant", catalog = "itaid")
public class VacacionesAnt implements java.io.Serializable {

	private Integer id;
	private String noEmpleado;
	private Date fechaIngreso;
	private String nombre;
	private String puesto;
	private String areaTienda;
	private String periodo;
	private Integer diasAcumulados;
	private Integer diasRestantes;
	private Integer duracion;
	private Date fechaIni;
	private Date fechaFin;
	private Integer goceSueldo;
	private String motivo;
	private String solicita;
	private String autoriza;
	private String vistoBueno;
	private Date fechaAlta;
	private String empresa;
	private String region;
	private String departamento;

	public VacacionesAnt() {
	}

	public VacacionesAnt(Date fechaAlta, String empresa, String region, String departamento) {
		this.fechaAlta = fechaAlta;
		this.empresa = empresa;
		this.region = region;
		this.departamento = departamento;
	}

	public VacacionesAnt(String noEmpleado, Date fechaIngreso, String nombre, String puesto, String areaTienda,
			String periodo, Integer diasAcumulados, Integer diasRestantes, Integer duracion, Date fechaIni,
			Date fechaFin, Integer goceSueldo, String motivo, String solicita, String autoriza, String vistoBueno,
			Date fechaAlta, String empresa, String region, String departamento) {
		this.noEmpleado = noEmpleado;
		this.fechaIngreso = fechaIngreso;
		this.nombre = nombre;
		this.puesto = puesto;
		this.areaTienda = areaTienda;
		this.periodo = periodo;
		this.diasAcumulados = diasAcumulados;
		this.diasRestantes = diasRestantes;
		this.duracion = duracion;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.goceSueldo = goceSueldo;
		this.motivo = motivo;
		this.solicita = solicita;
		this.autoriza = autoriza;
		this.vistoBueno = vistoBueno;
		this.fechaAlta = fechaAlta;
		this.empresa = empresa;
		this.region = region;
		this.departamento = departamento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "no_empleado", length = 10)
	public String getNoEmpleado() {
		return this.noEmpleado;
	}

	public void setNoEmpleado(String noEmpleado) {
		this.noEmpleado = noEmpleado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", length = 10)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "nombre", length = 65535)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "puesto", length = 45)
	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	@Column(name = "area_tienda", length = 45)
	public String getAreaTienda() {
		return this.areaTienda;
	}

	public void setAreaTienda(String areaTienda) {
		this.areaTienda = areaTienda;
	}

	@Column(name = "periodo", length = 45)
	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	@Column(name = "dias_acumulados")
	public Integer getDiasAcumulados() {
		return this.diasAcumulados;
	}

	public void setDiasAcumulados(Integer diasAcumulados) {
		this.diasAcumulados = diasAcumulados;
	}

	@Column(name = "dias_restantes")
	public Integer getDiasRestantes() {
		return this.diasRestantes;
	}

	public void setDiasRestantes(Integer diasRestantes) {
		this.diasRestantes = diasRestantes;
	}

	@Column(name = "duracion")
	public Integer getDuracion() {
		return this.duracion;
	}

	public void setDuracion(Integer duracion) {
		this.duracion = duracion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ini", length = 10)
	public Date getFechaIni() {
		return this.fechaIni;
	}

	public void setFechaIni(Date fechaIni) {
		this.fechaIni = fechaIni;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "goce_sueldo")
	public Integer getGoceSueldo() {
		return this.goceSueldo;
	}

	public void setGoceSueldo(Integer goceSueldo) {
		this.goceSueldo = goceSueldo;
	}

	@Column(name = "motivo", length = 65535)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "solicita", length = 150)
	public String getSolicita() {
		return this.solicita;
	}

	public void setSolicita(String solicita) {
		this.solicita = solicita;
	}

	@Column(name = "autoriza", length = 150)
	public String getAutoriza() {
		return this.autoriza;
	}

	public void setAutoriza(String autoriza) {
		this.autoriza = autoriza;
	}

	@Column(name = "vistoBueno", length = 150)
	public String getVistoBueno() {
		return this.vistoBueno;
	}

	public void setVistoBueno(String vistoBueno) {
		this.vistoBueno = vistoBueno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "empresa", nullable = false, length = 150)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Column(name = "region", nullable = false, length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "departamento", nullable = false, length = 50)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

}
