package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name = "accion", catalog = "itaid")
public class Accion implements java.io.Serializable {

	private Integer id;
	private int ticketId;
	private Date fecha;
	private String descripcion;
	private int tecnicoId;
	private Integer proveedorId;

	public Accion() {
	}

	public Accion(int ticketId, Date fecha, String descripcion, int tecnicoId) {
		this.ticketId = ticketId;
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.tecnicoId = tecnicoId;
	}

	public Accion(int ticketId, Date fecha, String descripcion, int tecnicoId, Integer proveedorId) {
		this.ticketId = ticketId;
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.tecnicoId = tecnicoId;
		this.proveedorId = proveedorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ticket_id", nullable = false)
	public int getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(int ticketId) {
		this.ticketId = ticketId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "tecnico_id", nullable = false)
	public int getTecnicoId() {
		return this.tecnicoId;
	}

	public void setTecnicoId(int tecnicoId) {
		this.tecnicoId = tecnicoId;
	}

	@Column(name = "proveedor_id")
	public Integer getProveedorId() {
		return this.proveedorId;
	}

	public void setProveedorId(Integer proveedorId) {
		this.proveedorId = proveedorId;
	}

}
