package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActivoInventario generated by hbm2java
 */
@Entity
@Table(name = "activo_inventario", catalog = "itaid")
public class ActivoInventario implements java.io.Serializable {

	private ActivoInventarioId id;

	public ActivoInventario() {
	}

	public ActivoInventario(ActivoInventarioId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "activo", column = @Column(name = "activo", length = 70)),
			@AttributeOverride(name = "serie", column = @Column(name = "serie", length = 24)),
			@AttributeOverride(name = "tag", column = @Column(name = "tag", length = 20)),
			@AttributeOverride(name = "costo", column = @Column(name = "costo", nullable = false, precision = 7)),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", nullable = false, length = 25)),
			@AttributeOverride(name = "asignado", column = @Column(name = "asignado", length = 51)) })
	public ActivoInventarioId getId() {
		return this.id;
	}

	public void setId(ActivoInventarioId id) {
		this.id = id;
	}

}
