package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Arrendadores generated by hbm2java
 */
@Entity
@Table(name = "arrendadores", catalog = "itaid", uniqueConstraints = @UniqueConstraint(columnNames = "rfc"))
public class Arrendadores implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String domicilio;
	private String telefono;
	private String rfc;
	private String observaciones;
	private Integer estadoRentasId;
	private String correoElectronico;
	private String clave;
	private String extension;
	private String cuenta;
	private String contacto;
	private String arrendadorescol;
	private int diasEntrega;
	private int diasPago;

	public Arrendadores() {
	}

	public Arrendadores(String nombre, String clave, String cuenta, String contacto, int diasEntrega, int diasPago) {
		this.nombre = nombre;
		this.clave = clave;
		this.cuenta = cuenta;
		this.contacto = contacto;
		this.diasEntrega = diasEntrega;
		this.diasPago = diasPago;
	}

	public Arrendadores(String nombre, String domicilio, String telefono, String rfc, String observaciones,
			Integer estadoRentasId, String correoElectronico, String clave, String extension, String cuenta,
			String contacto, String arrendadorescol, int diasEntrega, int diasPago) {
		this.nombre = nombre;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.rfc = rfc;
		this.observaciones = observaciones;
		this.estadoRentasId = estadoRentasId;
		this.correoElectronico = correoElectronico;
		this.clave = clave;
		this.extension = extension;
		this.cuenta = cuenta;
		this.contacto = contacto;
		this.arrendadorescol = arrendadorescol;
		this.diasEntrega = diasEntrega;
		this.diasPago = diasPago;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 250)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "domicilio", length = 65535)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "rfc", unique = true, length = 20)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "observaciones", length = 65535)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "estado_rentas_id")
	public Integer getEstadoRentasId() {
		return this.estadoRentasId;
	}

	public void setEstadoRentasId(Integer estadoRentasId) {
		this.estadoRentasId = estadoRentasId;
	}

	@Column(name = "correo_electronico", length = 250)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "clave", nullable = false, length = 4)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "extension", length = 5)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "cuenta", nullable = false, length = 65535)
	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	@Column(name = "contacto", nullable = false, length = 50)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "arrendadorescol", length = 45)
	public String getArrendadorescol() {
		return this.arrendadorescol;
	}

	public void setArrendadorescol(String arrendadorescol) {
		this.arrendadorescol = arrendadorescol;
	}

	@Column(name = "diasEntrega", nullable = false)
	public int getDiasEntrega() {
		return this.diasEntrega;
	}

	public void setDiasEntrega(int diasEntrega) {
		this.diasEntrega = diasEntrega;
	}

	@Column(name = "diasPago", nullable = false)
	public int getDiasPago() {
		return this.diasPago;
	}

	public void setDiasPago(int diasPago) {
		this.diasPago = diasPago;
	}

}
