package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CelAparato generated by hbm2java
 */
@Entity
@Table(name = "cel_aparato", catalog = "itaid")
public class CelAparato implements java.io.Serializable {

	private int id;
	private int activomodeloId;
	private String factura;
	private BigDecimal valorfactura;
	private String imei;
	private int estado;
	private String ultimoasignatarioId;

	public CelAparato() {
	}

	public CelAparato(int id, int activomodeloId, String factura, BigDecimal valorfactura, String imei, int estado) {
		this.id = id;
		this.activomodeloId = activomodeloId;
		this.factura = factura;
		this.valorfactura = valorfactura;
		this.imei = imei;
		this.estado = estado;
	}

	public CelAparato(int id, int activomodeloId, String factura, BigDecimal valorfactura, String imei, int estado,
			String ultimoasignatarioId) {
		this.id = id;
		this.activomodeloId = activomodeloId;
		this.factura = factura;
		this.valorfactura = valorfactura;
		this.imei = imei;
		this.estado = estado;
		this.ultimoasignatarioId = ultimoasignatarioId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "activomodelo_id", nullable = false)
	public int getActivomodeloId() {
		return this.activomodeloId;
	}

	public void setActivomodeloId(int activomodeloId) {
		this.activomodeloId = activomodeloId;
	}

	@Column(name = "factura", nullable = false, length = 10)
	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	@Column(name = "valorfactura", nullable = false, precision = 7)
	public BigDecimal getValorfactura() {
		return this.valorfactura;
	}

	public void setValorfactura(BigDecimal valorfactura) {
		this.valorfactura = valorfactura;
	}

	@Column(name = "imei", nullable = false, length = 15)
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "ultimoasignatario_id", length = 5)
	public String getUltimoasignatarioId() {
		return this.ultimoasignatarioId;
	}

	public void setUltimoasignatarioId(String ultimoasignatarioId) {
		this.ultimoasignatarioId = ultimoasignatarioId;
	}

}
