package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CelPaquete generated by hbm2java
 */
@Entity
@Table(name = "cel_paquete", catalog = "itaid")
public class CelPaquete implements java.io.Serializable {

	private int id;
	private String nombre;
	private String descripcion;
	private BigDecimal costo;

	public CelPaquete() {
	}

	public CelPaquete(int id, String nombre, BigDecimal costo) {
		this.id = id;
		this.nombre = nombre;
		this.costo = costo;
	}

	public CelPaquete(int id, String nombre, String descripcion, BigDecimal costo) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.costo = costo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "costo", nullable = false, precision = 7)
	public BigDecimal getCosto() {
		return this.costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

}
