package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CelPlan generated by hbm2java
 */
@Entity
@Table(name = "cel_plan", catalog = "itaid")
public class CelPlan implements java.io.Serializable {

	private int id;
	private String nombre;
	private String descripcion;
	private BigDecimal renta;
	private int penalizacion;

	public CelPlan() {
	}

	public CelPlan(int id, String nombre, String descripcion, BigDecimal renta, int penalizacion) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.renta = renta;
		this.penalizacion = penalizacion;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "renta", nullable = false, precision = 7)
	public BigDecimal getRenta() {
		return this.renta;
	}

	public void setRenta(BigDecimal renta) {
		this.renta = renta;
	}

	@Column(name = "penalizacion", nullable = false)
	public int getPenalizacion() {
		return this.penalizacion;
	}

	public void setPenalizacion(int penalizacion) {
		this.penalizacion = penalizacion;
	}

}
