package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Distritos generated by hbm2java
 */
@Entity
@Table(name = "distritos", catalog = "itaid")
public class Distritos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String clave;
	private String descripcion;
	private int responsableId;
	private Date dateCreate;
	private int userCreate;
	private Date dateModify;
	private int userModify;
	private boolean status;

	public Distritos() {
	}

	public Distritos(String nombre, String clave, String descripcion, int responsableId, Date dateCreate,
			int userCreate, Date dateModify, int userModify, boolean status) {
		this.nombre = nombre;
		this.clave = clave;
		this.descripcion = descripcion;
		this.responsableId = responsableId;
		this.dateCreate = dateCreate;
		this.userCreate = userCreate;
		this.dateModify = dateModify;
		this.userModify = userModify;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", nullable = false, length = 10)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "descripcion", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "responsable_id", nullable = false)
	public int getResponsableId() {
		return this.responsableId;
	}

	public void setResponsableId(int responsableId) {
		this.responsableId = responsableId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_create", nullable = false, length = 19)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "user_create", nullable = false)
	public int getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(int userCreate) {
		this.userCreate = userCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modify", nullable = false, length = 19)
	public Date getDateModify() {
		return this.dateModify;
	}

	public void setDateModify(Date dateModify) {
		this.dateModify = dateModify;
	}

	@Column(name = "user_modify", nullable = false)
	public int getUserModify() {
		return this.userModify;
	}

	public void setUserModify(int userModify) {
		this.userModify = userModify;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
