package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DistritosSucursales generated by hbm2java
 */
@Entity
@Table(name = "distritos_sucursales", catalog = "itaid")
public class DistritosSucursales implements java.io.Serializable {

	private Integer id;
	private int distritoId;
	private int sucursalId;
	private Date dateCreate;
	private int userCreate;
	private Date dateModify;
	private int userModify;
	private boolean status;

	public DistritosSucursales() {
	}

	public DistritosSucursales(int distritoId, int sucursalId, Date dateCreate, int userCreate, Date dateModify,
			int userModify, boolean status) {
		this.distritoId = distritoId;
		this.sucursalId = sucursalId;
		this.dateCreate = dateCreate;
		this.userCreate = userCreate;
		this.dateModify = dateModify;
		this.userModify = userModify;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "distrito_id", nullable = false)
	public int getDistritoId() {
		return this.distritoId;
	}

	public void setDistritoId(int distritoId) {
		this.distritoId = distritoId;
	}

	@Column(name = "sucursal_id", nullable = false)
	public int getSucursalId() {
		return this.sucursalId;
	}

	public void setSucursalId(int sucursalId) {
		this.sucursalId = sucursalId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_create", nullable = false, length = 19)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "user_create", nullable = false)
	public int getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(int userCreate) {
		this.userCreate = userCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modify", nullable = false, length = 19)
	public Date getDateModify() {
		return this.dateModify;
	}

	public void setDateModify(Date dateModify) {
		this.dateModify = dateModify;
	}

	@Column(name = "user_modify", nullable = false)
	public int getUserModify() {
		return this.userModify;
	}

	public void setUserModify(int userModify) {
		this.userModify = userModify;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
