package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EprojectPeUsuarioTmp generated by hbm2java
 */
@Entity
@Table(name = "eproject_pe_usuario_tmp", catalog = "itaid")
public class EprojectPeUsuarioTmp implements java.io.Serializable {

	private Integer id;
	private int peupeId;
	private int peuuserId;
	private int peuver;
	private int usercreate;
	private Date fechacreate;
	private int usermod;
	private Date fechamod;
	private Integer userdel;
	private Date fechadel;
	private int status;

	public EprojectPeUsuarioTmp() {
	}

	public EprojectPeUsuarioTmp(int peupeId, int peuuserId, int peuver, int usercreate, Date fechacreate, int usermod,
			int status) {
		this.peupeId = peupeId;
		this.peuuserId = peuuserId;
		this.peuver = peuver;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.usermod = usermod;
		this.status = status;
	}

	public EprojectPeUsuarioTmp(int peupeId, int peuuserId, int peuver, int usercreate, Date fechacreate, int usermod,
			Date fechamod, Integer userdel, Date fechadel, int status) {
		this.peupeId = peupeId;
		this.peuuserId = peuuserId;
		this.peuver = peuver;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.usermod = usermod;
		this.fechamod = fechamod;
		this.userdel = userdel;
		this.fechadel = fechadel;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "peupe_id", nullable = false)
	public int getPeupeId() {
		return this.peupeId;
	}

	public void setPeupeId(int peupeId) {
		this.peupeId = peupeId;
	}

	@Column(name = "peuuser_id", nullable = false)
	public int getPeuuserId() {
		return this.peuuserId;
	}

	public void setPeuuserId(int peuuserId) {
		this.peuuserId = peuuserId;
	}

	@Column(name = "peuver", nullable = false)
	public int getPeuver() {
		return this.peuver;
	}

	public void setPeuver(int peuver) {
		this.peuver = peuver;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreate", nullable = false, length = 10)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "usermod", nullable = false)
	public int getUsermod() {
		return this.usermod;
	}

	public void setUsermod(int usermod) {
		this.usermod = usermod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamod", length = 10)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "userdel")
	public Integer getUserdel() {
		return this.userdel;
	}

	public void setUserdel(Integer userdel) {
		this.userdel = userdel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechadel", length = 10)
	public Date getFechadel() {
		return this.fechadel;
	}

	public void setFechadel(Date fechadel) {
		this.fechadel = fechadel;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
