package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EprojectTiposUsuario generated by hbm2java
 */
@Entity
@Table(name = "eproject_tipos_usuario", catalog = "itaid")
public class EprojectTiposUsuario implements java.io.Serializable {

	private Integer id;
	private String tunombre;
	private String tudescripcion;
	private String tuidentificador;
	private int usercreate;
	private Date fechacreate;
	private Integer usermod;
	private Date fechamod;
	private Integer userdel;
	private Date fechadel;
	private String status;

	public EprojectTiposUsuario() {
	}

	public EprojectTiposUsuario(String tunombre, String tudescripcion, String tuidentificador, int usercreate,
			Date fechacreate, String status) {
		this.tunombre = tunombre;
		this.tudescripcion = tudescripcion;
		this.tuidentificador = tuidentificador;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.status = status;
	}

	public EprojectTiposUsuario(String tunombre, String tudescripcion, String tuidentificador, int usercreate,
			Date fechacreate, Integer usermod, Date fechamod, Integer userdel, Date fechadel, String status) {
		this.tunombre = tunombre;
		this.tudescripcion = tudescripcion;
		this.tuidentificador = tuidentificador;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.usermod = usermod;
		this.fechamod = fechamod;
		this.userdel = userdel;
		this.fechadel = fechadel;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tunombre", nullable = false, length = 65535)
	public String getTunombre() {
		return this.tunombre;
	}

	public void setTunombre(String tunombre) {
		this.tunombre = tunombre;
	}

	@Column(name = "tudescripcion", nullable = false, length = 65535)
	public String getTudescripcion() {
		return this.tudescripcion;
	}

	public void setTudescripcion(String tudescripcion) {
		this.tudescripcion = tudescripcion;
	}

	@Column(name = "tuidentificador", nullable = false, length = 10)
	public String getTuidentificador() {
		return this.tuidentificador;
	}

	public void setTuidentificador(String tuidentificador) {
		this.tuidentificador = tuidentificador;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreate", nullable = false, length = 10)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "usermod")
	public Integer getUsermod() {
		return this.usermod;
	}

	public void setUsermod(Integer usermod) {
		this.usermod = usermod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamod", length = 10)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "userdel")
	public Integer getUserdel() {
		return this.userdel;
	}

	public void setUserdel(Integer userdel) {
		this.userdel = userdel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechadel", length = 10)
	public Date getFechadel() {
		return this.fechadel;
	}

	public void setFechadel(Date fechadel) {
		this.fechadel = fechadel;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
