package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EprojectLogProyecto generated by hbm2java
 */
@Entity
@Table(name = "eproject_log_proyecto", catalog = "itaid")
public class EprojectLogProyecto implements java.io.Serializable {

	private Integer id;
	private int lpproyectoId;
	private int lpetapaId;
	private int lptipoId;
	private int lpuserId;
	private String lpasunto;
	private String lptexto;
	private Date fecha;

	public EprojectLogProyecto() {
	}

	public EprojectLogProyecto(int lpproyectoId, int lpetapaId, int lptipoId, int lpuserId, String lpasunto,
			String lptexto, Date fecha) {
		this.lpproyectoId = lpproyectoId;
		this.lpetapaId = lpetapaId;
		this.lptipoId = lptipoId;
		this.lpuserId = lpuserId;
		this.lpasunto = lpasunto;
		this.lptexto = lptexto;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "lpproyecto_id", nullable = false)
	public int getLpproyectoId() {
		return this.lpproyectoId;
	}

	public void setLpproyectoId(int lpproyectoId) {
		this.lpproyectoId = lpproyectoId;
	}

	@Column(name = "lpetapa_id", nullable = false)
	public int getLpetapaId() {
		return this.lpetapaId;
	}

	public void setLpetapaId(int lpetapaId) {
		this.lpetapaId = lpetapaId;
	}

	@Column(name = "lptipo_id", nullable = false)
	public int getLptipoId() {
		return this.lptipoId;
	}

	public void setLptipoId(int lptipoId) {
		this.lptipoId = lptipoId;
	}

	@Column(name = "lpuser_id", nullable = false)
	public int getLpuserId() {
		return this.lpuserId;
	}

	public void setLpuserId(int lpuserId) {
		this.lpuserId = lpuserId;
	}

	@Column(name = "lpasunto", nullable = false, length = 65535)
	public String getLpasunto() {
		return this.lpasunto;
	}

	public void setLpasunto(String lpasunto) {
		this.lpasunto = lpasunto;
	}

	@Column(name = "lptexto", nullable = false, length = 65535)
	public String getLptexto() {
		return this.lptexto;
	}

	public void setLptexto(String lptexto) {
		this.lptexto = lptexto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
