package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EprojectMensaje generated by hbm2java
 */
@Entity
@Table(name = "eproject_mensaje", catalog = "itaid")
public class EprojectMensaje implements java.io.Serializable {

	private Integer id;
	private String mpara;
	private String mde;
	private String masunto;
	private String mfuente;
	private int mfuenteId;
	private String mmensaje;
	private int usercreate;
	private Date fechacreate;
	private int status;

	public EprojectMensaje() {
	}

	public EprojectMensaje(String mpara, String mde, String masunto, String mfuente, int mfuenteId, String mmensaje,
			int usercreate, Date fechacreate, int status) {
		this.mpara = mpara;
		this.mde = mde;
		this.masunto = masunto;
		this.mfuente = mfuente;
		this.mfuenteId = mfuenteId;
		this.mmensaje = mmensaje;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mpara", nullable = false, length = 65535)
	public String getMpara() {
		return this.mpara;
	}

	public void setMpara(String mpara) {
		this.mpara = mpara;
	}

	@Column(name = "mde", nullable = false, length = 65535)
	public String getMde() {
		return this.mde;
	}

	public void setMde(String mde) {
		this.mde = mde;
	}

	@Column(name = "masunto", nullable = false, length = 65535)
	public String getMasunto() {
		return this.masunto;
	}

	public void setMasunto(String masunto) {
		this.masunto = masunto;
	}

	@Column(name = "mfuente", nullable = false, length = 45)
	public String getMfuente() {
		return this.mfuente;
	}

	public void setMfuente(String mfuente) {
		this.mfuente = mfuente;
	}

	@Column(name = "mfuente_id", nullable = false)
	public int getMfuenteId() {
		return this.mfuenteId;
	}

	public void setMfuenteId(int mfuenteId) {
		this.mfuenteId = mfuenteId;
	}

	@Column(name = "mmensaje", nullable = false, length = 65535)
	public String getMmensaje() {
		return this.mmensaje;
	}

	public void setMmensaje(String mmensaje) {
		this.mmensaje = mmensaje;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreate", nullable = false, length = 10)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
