package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EprojectEtapas generated by hbm2java
 */
@Entity
@Table(name = "eproject_etapas", catalog = "itaid")
public class EprojectEtapas implements java.io.Serializable {

	private Integer id;
	private String enombre;
	private String edescripcion;
	private String eidentificador;
	private int edefault;
	private int usercreate;
	private Date fechacreate;
	private Integer usermod;
	private Date fechamod;
	private Integer userdel;
	private Date fechadel;
	private int status;
	private int orden;

	public EprojectEtapas() {
	}

	public EprojectEtapas(String enombre, String edescripcion, String eidentificador, int edefault, int usercreate,
			Date fechacreate, int status, int orden) {
		this.enombre = enombre;
		this.edescripcion = edescripcion;
		this.eidentificador = eidentificador;
		this.edefault = edefault;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.status = status;
		this.orden = orden;
	}

	public EprojectEtapas(String enombre, String edescripcion, String eidentificador, int edefault, int usercreate,
			Date fechacreate, Integer usermod, Date fechamod, Integer userdel, Date fechadel, int status, int orden) {
		this.enombre = enombre;
		this.edescripcion = edescripcion;
		this.eidentificador = eidentificador;
		this.edefault = edefault;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.usermod = usermod;
		this.fechamod = fechamod;
		this.userdel = userdel;
		this.fechadel = fechadel;
		this.status = status;
		this.orden = orden;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "enombre", nullable = false, length = 65535)
	public String getEnombre() {
		return this.enombre;
	}

	public void setEnombre(String enombre) {
		this.enombre = enombre;
	}

	@Column(name = "edescripcion", nullable = false, length = 65535)
	public String getEdescripcion() {
		return this.edescripcion;
	}

	public void setEdescripcion(String edescripcion) {
		this.edescripcion = edescripcion;
	}

	@Column(name = "eidentificador", nullable = false, length = 10)
	public String getEidentificador() {
		return this.eidentificador;
	}

	public void setEidentificador(String eidentificador) {
		this.eidentificador = eidentificador;
	}

	@Column(name = "edefault", nullable = false)
	public int getEdefault() {
		return this.edefault;
	}

	public void setEdefault(int edefault) {
		this.edefault = edefault;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreate", nullable = false, length = 10)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "usermod")
	public Integer getUsermod() {
		return this.usermod;
	}

	public void setUsermod(Integer usermod) {
		this.usermod = usermod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamod", length = 10)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "userdel")
	public Integer getUserdel() {
		return this.userdel;
	}

	public void setUserdel(Integer userdel) {
		this.userdel = userdel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechadel", length = 10)
	public Date getFechadel() {
		return this.fechadel;
	}

	public void setFechadel(Date fechadel) {
		this.fechadel = fechadel;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

}
