package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EprojectProyectoEtapa generated by hbm2java
 */
@Entity
@Table(name = "eproject_proyecto_etapa", catalog = "itaid")
public class EprojectProyectoEtapa implements java.io.Serializable {

	private Integer id;
	private int peproyectoId;
	private int peetapaId;
	private Date pefechaInicio;
	private Date pefechaFin;
	private String pedescripcion;
	private int peuserEncargado;
	private int pestatus;
	private int usercreate;
	private Date fechacreate;
	private Integer usermod;
	private Date fechamod;
	private Integer userdel;
	private Date fechadel;
	private int status;

	public EprojectProyectoEtapa() {
	}

	public EprojectProyectoEtapa(int peproyectoId, int peetapaId, Date pefechaInicio, Date pefechaFin,
			int peuserEncargado, int pestatus, int usercreate, Date fechacreate, int status) {
		this.peproyectoId = peproyectoId;
		this.peetapaId = peetapaId;
		this.pefechaInicio = pefechaInicio;
		this.pefechaFin = pefechaFin;
		this.peuserEncargado = peuserEncargado;
		this.pestatus = pestatus;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.status = status;
	}

	public EprojectProyectoEtapa(int peproyectoId, int peetapaId, Date pefechaInicio, Date pefechaFin,
			String pedescripcion, int peuserEncargado, int pestatus, int usercreate, Date fechacreate, Integer usermod,
			Date fechamod, Integer userdel, Date fechadel, int status) {
		this.peproyectoId = peproyectoId;
		this.peetapaId = peetapaId;
		this.pefechaInicio = pefechaInicio;
		this.pefechaFin = pefechaFin;
		this.pedescripcion = pedescripcion;
		this.peuserEncargado = peuserEncargado;
		this.pestatus = pestatus;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.usermod = usermod;
		this.fechamod = fechamod;
		this.userdel = userdel;
		this.fechadel = fechadel;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "peproyecto_id", nullable = false)
	public int getPeproyectoId() {
		return this.peproyectoId;
	}

	public void setPeproyectoId(int peproyectoId) {
		this.peproyectoId = peproyectoId;
	}

	@Column(name = "peetapa_id", nullable = false)
	public int getPeetapaId() {
		return this.peetapaId;
	}

	public void setPeetapaId(int peetapaId) {
		this.peetapaId = peetapaId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pefecha_inicio", nullable = false, length = 10)
	public Date getPefechaInicio() {
		return this.pefechaInicio;
	}

	public void setPefechaInicio(Date pefechaInicio) {
		this.pefechaInicio = pefechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pefecha_fin", nullable = false, length = 10)
	public Date getPefechaFin() {
		return this.pefechaFin;
	}

	public void setPefechaFin(Date pefechaFin) {
		this.pefechaFin = pefechaFin;
	}

	@Column(name = "pedescripcion", length = 100)
	public String getPedescripcion() {
		return this.pedescripcion;
	}

	public void setPedescripcion(String pedescripcion) {
		this.pedescripcion = pedescripcion;
	}

	@Column(name = "peuser_encargado", nullable = false)
	public int getPeuserEncargado() {
		return this.peuserEncargado;
	}

	public void setPeuserEncargado(int peuserEncargado) {
		this.peuserEncargado = peuserEncargado;
	}

	@Column(name = "pestatus", nullable = false)
	public int getPestatus() {
		return this.pestatus;
	}

	public void setPestatus(int pestatus) {
		this.pestatus = pestatus;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreate", nullable = false, length = 10)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "usermod")
	public Integer getUsermod() {
		return this.usermod;
	}

	public void setUsermod(Integer usermod) {
		this.usermod = usermod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamod", length = 10)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "userdel")
	public Integer getUserdel() {
		return this.userdel;
	}

	public void setUserdel(Integer userdel) {
		this.userdel = userdel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechadel", length = 10)
	public Date getFechadel() {
		return this.fechadel;
	}

	public void setFechadel(Date fechadel) {
		this.fechadel = fechadel;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
