package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EprojectProyecto generated by hbm2java
 */
@Entity
@Table(name = "eproject_proyecto", catalog = "itaid")
public class EprojectProyecto implements java.io.Serializable {

	private Integer id;
	private String pnombre;
	private String pdescripcion;
	private String pidentificador;
	private int pencargadoId;
	private Date pfechaInicio;
	private Date pfechaFin;
	private int pcorreoAut;
	private int pticketVencido;
	private Integer pliderId;
	private Integer ptecnicoId;
	private Integer pusuarioId;
	private int usercreate;
	private Date fechacreate;
	private Integer usermod;
	private Date fechamod;
	private Integer userdel;
	private Date fechadel;
	private int status;

	public EprojectProyecto() {
	}

	public EprojectProyecto(String pnombre, String pdescripcion, String pidentificador, int pencargadoId,
			Date pfechaInicio, Date pfechaFin, int pcorreoAut, int pticketVencido, int usercreate, Date fechacreate,
			int status) {
		this.pnombre = pnombre;
		this.pdescripcion = pdescripcion;
		this.pidentificador = pidentificador;
		this.pencargadoId = pencargadoId;
		this.pfechaInicio = pfechaInicio;
		this.pfechaFin = pfechaFin;
		this.pcorreoAut = pcorreoAut;
		this.pticketVencido = pticketVencido;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.status = status;
	}

	public EprojectProyecto(String pnombre, String pdescripcion, String pidentificador, int pencargadoId,
			Date pfechaInicio, Date pfechaFin, int pcorreoAut, int pticketVencido, Integer pliderId, Integer ptecnicoId,
			Integer pusuarioId, int usercreate, Date fechacreate, Integer usermod, Date fechamod, Integer userdel,
			Date fechadel, int status) {
		this.pnombre = pnombre;
		this.pdescripcion = pdescripcion;
		this.pidentificador = pidentificador;
		this.pencargadoId = pencargadoId;
		this.pfechaInicio = pfechaInicio;
		this.pfechaFin = pfechaFin;
		this.pcorreoAut = pcorreoAut;
		this.pticketVencido = pticketVencido;
		this.pliderId = pliderId;
		this.ptecnicoId = ptecnicoId;
		this.pusuarioId = pusuarioId;
		this.usercreate = usercreate;
		this.fechacreate = fechacreate;
		this.usermod = usermod;
		this.fechamod = fechamod;
		this.userdel = userdel;
		this.fechadel = fechadel;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pnombre", nullable = false, length = 65535)
	public String getPnombre() {
		return this.pnombre;
	}

	public void setPnombre(String pnombre) {
		this.pnombre = pnombre;
	}

	@Column(name = "pdescripcion", nullable = false, length = 65535)
	public String getPdescripcion() {
		return this.pdescripcion;
	}

	public void setPdescripcion(String pdescripcion) {
		this.pdescripcion = pdescripcion;
	}

	@Column(name = "pidentificador", nullable = false, length = 10)
	public String getPidentificador() {
		return this.pidentificador;
	}

	public void setPidentificador(String pidentificador) {
		this.pidentificador = pidentificador;
	}

	@Column(name = "pencargado_id", nullable = false)
	public int getPencargadoId() {
		return this.pencargadoId;
	}

	public void setPencargadoId(int pencargadoId) {
		this.pencargadoId = pencargadoId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pfecha_inicio", nullable = false, length = 10)
	public Date getPfechaInicio() {
		return this.pfechaInicio;
	}

	public void setPfechaInicio(Date pfechaInicio) {
		this.pfechaInicio = pfechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pfecha_fin", nullable = false, length = 10)
	public Date getPfechaFin() {
		return this.pfechaFin;
	}

	public void setPfechaFin(Date pfechaFin) {
		this.pfechaFin = pfechaFin;
	}

	@Column(name = "pcorreo_aut", nullable = false)
	public int getPcorreoAut() {
		return this.pcorreoAut;
	}

	public void setPcorreoAut(int pcorreoAut) {
		this.pcorreoAut = pcorreoAut;
	}

	@Column(name = "pticket_vencido", nullable = false)
	public int getPticketVencido() {
		return this.pticketVencido;
	}

	public void setPticketVencido(int pticketVencido) {
		this.pticketVencido = pticketVencido;
	}

	@Column(name = "plider_id")
	public Integer getPliderId() {
		return this.pliderId;
	}

	public void setPliderId(Integer pliderId) {
		this.pliderId = pliderId;
	}

	@Column(name = "ptecnico_id")
	public Integer getPtecnicoId() {
		return this.ptecnicoId;
	}

	public void setPtecnicoId(Integer ptecnicoId) {
		this.ptecnicoId = ptecnicoId;
	}

	@Column(name = "pusuario_id")
	public Integer getPusuarioId() {
		return this.pusuarioId;
	}

	public void setPusuarioId(Integer pusuarioId) {
		this.pusuarioId = pusuarioId;
	}

	@Column(name = "usercreate", nullable = false)
	public int getUsercreate() {
		return this.usercreate;
	}

	public void setUsercreate(int usercreate) {
		this.usercreate = usercreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreate", nullable = false, length = 10)
	public Date getFechacreate() {
		return this.fechacreate;
	}

	public void setFechacreate(Date fechacreate) {
		this.fechacreate = fechacreate;
	}

	@Column(name = "usermod")
	public Integer getUsermod() {
		return this.usermod;
	}

	public void setUsermod(Integer usermod) {
		this.usermod = usermod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamod", length = 10)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "userdel")
	public Integer getUserdel() {
		return this.userdel;
	}

	public void setUserdel(Integer userdel) {
		this.userdel = userdel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechadel", length = 10)
	public Date getFechadel() {
		return this.fechadel;
	}

	public void setFechadel(Date fechadel) {
		this.fechadel = fechadel;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
