package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Equipostockregion generated by hbm2java
 */
@Entity
@Table(name = "equipostockregion", catalog = "itaid", uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class Equipostockregion implements java.io.Serializable {

	private EquipostockregionId id;
	private int id_1;
	private String stock;
	private String hora;
	private String usuario;

	public Equipostockregion() {
	}

	public Equipostockregion(EquipostockregionId id, int id_1) {
		this.id = id;
		this.id_1 = id_1;
	}

	public Equipostockregion(EquipostockregionId id, int id_1, String stock, String hora, String usuario) {
		this.id = id;
		this.id_1 = id_1;
		this.stock = stock;
		this.hora = hora;
		this.usuario = usuario;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "equipo", column = @Column(name = "equipo", nullable = false)),
			@AttributeOverride(name = "tienda", column = @Column(name = "tienda", nullable = false, length = 10)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 10)),
			@AttributeOverride(name = "region", column = @Column(name = "region", nullable = false, length = 10)) })
	public EquipostockregionId getId() {
		return this.id;
	}

	public void setId(EquipostockregionId id) {
		this.id = id;
	}

	@Column(name = "id", unique = true, nullable = false)
	public int getId_1() {
		return this.id_1;
	}

	public void setId_1(int id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "stock", length = 50)
	public String getStock() {
		return this.stock;
	}

	public void setStock(String stock) {
		this.stock = stock;
	}

	@Column(name = "hora", length = 50)
	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	@Column(name = "usuario", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

}
