package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eventos generated by hbm2java
 */
@Entity
@Table(name = "eventos", catalog = "itaid")
public class Eventos implements java.io.Serializable {

	private Integer id;
	private int headerEventoId;
	private String descripcion;
	private String comentarios;
	private Date fechaInicio;
	private Date fechaFin;
	private Date horaInicio;
	private Date horaFin;
	private int encargadoId;
	private Date fechaHora;
	private boolean status;

	public Eventos() {
	}

	public Eventos(int headerEventoId, String descripcion, String comentarios, Date fechaInicio, Date fechaFin,
			Date horaInicio, Date horaFin, int encargadoId, Date fechaHora, boolean status) {
		this.headerEventoId = headerEventoId;
		this.descripcion = descripcion;
		this.comentarios = comentarios;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.encargadoId = encargadoId;
		this.fechaHora = fechaHora;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "header_evento_id", nullable = false)
	public int getHeaderEventoId() {
		return this.headerEventoId;
	}

	public void setHeaderEventoId(int headerEventoId) {
		this.headerEventoId = headerEventoId;
	}

	@Column(name = "descripcion", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "comentarios", nullable = false, length = 65535)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", nullable = false, length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin", nullable = false, length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "encargado_id", nullable = false)
	public int getEncargadoId() {
		return this.encargadoId;
	}

	public void setEncargadoId(int encargadoId) {
		this.encargadoId = encargadoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = false, length = 19)
	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
