package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GastosReporte generated by hbm2java
 */
@Entity
@Table(name = "gastos_reporte", catalog = "itaid")
public class GastosReporte implements java.io.Serializable {

	private int id;
	private Date periodo;
	private Date fecha;
	private int solicitanteId;
	private int departamentoId;
	private String moneda;
	private BigDecimal importeTotal;
	private BigDecimal importeAnticipado;
	private BigDecimal importeAreembolsar;
	private BigDecimal importeAfavor;
	private Byte autArea;
	private Date fechaAutArea;
	private Byte autFinanciera;
	private Date fechaAutFinanciera;
	private int gastosEstadoId;
	private String observaciones;

	public GastosReporte() {
	}

	public GastosReporte(int id, Date periodo, Date fecha, int solicitanteId, int departamentoId, String moneda,
			BigDecimal importeTotal, BigDecimal importeAnticipado, BigDecimal importeAreembolsar,
			BigDecimal importeAfavor, int gastosEstadoId) {
		this.id = id;
		this.periodo = periodo;
		this.fecha = fecha;
		this.solicitanteId = solicitanteId;
		this.departamentoId = departamentoId;
		this.moneda = moneda;
		this.importeTotal = importeTotal;
		this.importeAnticipado = importeAnticipado;
		this.importeAreembolsar = importeAreembolsar;
		this.importeAfavor = importeAfavor;
		this.gastosEstadoId = gastosEstadoId;
	}

	public GastosReporte(int id, Date periodo, Date fecha, int solicitanteId, int departamentoId, String moneda,
			BigDecimal importeTotal, BigDecimal importeAnticipado, BigDecimal importeAreembolsar,
			BigDecimal importeAfavor, Byte autArea, Date fechaAutArea, Byte autFinanciera, Date fechaAutFinanciera,
			int gastosEstadoId, String observaciones) {
		this.id = id;
		this.periodo = periodo;
		this.fecha = fecha;
		this.solicitanteId = solicitanteId;
		this.departamentoId = departamentoId;
		this.moneda = moneda;
		this.importeTotal = importeTotal;
		this.importeAnticipado = importeAnticipado;
		this.importeAreembolsar = importeAreembolsar;
		this.importeAfavor = importeAfavor;
		this.autArea = autArea;
		this.fechaAutArea = fechaAutArea;
		this.autFinanciera = autFinanciera;
		this.fechaAutFinanciera = fechaAutFinanciera;
		this.gastosEstadoId = gastosEstadoId;
		this.observaciones = observaciones;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "periodo", nullable = false, length = 10)
	public Date getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Date periodo) {
		this.periodo = periodo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "solicitante_id", nullable = false)
	public int getSolicitanteId() {
		return this.solicitanteId;
	}

	public void setSolicitanteId(int solicitanteId) {
		this.solicitanteId = solicitanteId;
	}

	@Column(name = "departamento_id", nullable = false)
	public int getDepartamentoId() {
		return this.departamentoId;
	}

	public void setDepartamentoId(int departamentoId) {
		this.departamentoId = departamentoId;
	}

	@Column(name = "moneda", nullable = false, length = 3)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "importe_total", nullable = false, precision = 7)
	public BigDecimal getImporteTotal() {
		return this.importeTotal;
	}

	public void setImporteTotal(BigDecimal importeTotal) {
		this.importeTotal = importeTotal;
	}

	@Column(name = "importe_anticipado", nullable = false, precision = 7)
	public BigDecimal getImporteAnticipado() {
		return this.importeAnticipado;
	}

	public void setImporteAnticipado(BigDecimal importeAnticipado) {
		this.importeAnticipado = importeAnticipado;
	}

	@Column(name = "importe_areembolsar", nullable = false, precision = 7)
	public BigDecimal getImporteAreembolsar() {
		return this.importeAreembolsar;
	}

	public void setImporteAreembolsar(BigDecimal importeAreembolsar) {
		this.importeAreembolsar = importeAreembolsar;
	}

	@Column(name = "importe_afavor", nullable = false, precision = 7)
	public BigDecimal getImporteAfavor() {
		return this.importeAfavor;
	}

	public void setImporteAfavor(BigDecimal importeAfavor) {
		this.importeAfavor = importeAfavor;
	}

	@Column(name = "aut_area")
	public Byte getAutArea() {
		return this.autArea;
	}

	public void setAutArea(Byte autArea) {
		this.autArea = autArea;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_aut_area", length = 10)
	public Date getFechaAutArea() {
		return this.fechaAutArea;
	}

	public void setFechaAutArea(Date fechaAutArea) {
		this.fechaAutArea = fechaAutArea;
	}

	@Column(name = "aut_financiera")
	public Byte getAutFinanciera() {
		return this.autFinanciera;
	}

	public void setAutFinanciera(Byte autFinanciera) {
		this.autFinanciera = autFinanciera;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_aut_financiera", length = 10)
	public Date getFechaAutFinanciera() {
		return this.fechaAutFinanciera;
	}

	public void setFechaAutFinanciera(Date fechaAutFinanciera) {
		this.fechaAutFinanciera = fechaAutFinanciera;
	}

	@Column(name = "gastos_estado_id", nullable = false)
	public int getGastosEstadoId() {
		return this.gastosEstadoId;
	}

	public void setGastosEstadoId(int gastosEstadoId) {
		this.gastosEstadoId = gastosEstadoId;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
