package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GastosVer generated by hbm2java
 */
@Entity
@Table(name = "gastos_ver", catalog = "itaid")
public class GastosVer implements java.io.Serializable {

	private Integer id;
	private int headerGastoId;
	private Integer headerGastoVer;
	private int gastoid;
	private int userid;
	private Date fecha;
	private String comentario;
	private boolean status;

	public GastosVer() {
	}

	public GastosVer(int headerGastoId, int gastoid, int userid, Date fecha, String comentario, boolean status) {
		this.headerGastoId = headerGastoId;
		this.gastoid = gastoid;
		this.userid = userid;
		this.fecha = fecha;
		this.comentario = comentario;
		this.status = status;
	}

	public GastosVer(int headerGastoId, Integer headerGastoVer, int gastoid, int userid, Date fecha, String comentario,
			boolean status) {
		this.headerGastoId = headerGastoId;
		this.headerGastoVer = headerGastoVer;
		this.gastoid = gastoid;
		this.userid = userid;
		this.fecha = fecha;
		this.comentario = comentario;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "header_gasto_id", nullable = false)
	public int getHeaderGastoId() {
		return this.headerGastoId;
	}

	public void setHeaderGastoId(int headerGastoId) {
		this.headerGastoId = headerGastoId;
	}

	@Column(name = "header_gasto_ver")
	public Integer getHeaderGastoVer() {
		return this.headerGastoVer;
	}

	public void setHeaderGastoVer(Integer headerGastoVer) {
		this.headerGastoVer = headerGastoVer;
	}

	@Column(name = "gastoid", nullable = false)
	public int getGastoid() {
		return this.gastoid;
	}

	public void setGastoid(int gastoid) {
		this.gastoid = gastoid;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "comentario", nullable = false, length = 65535)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
