package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HeaderGastos generated by hbm2java
 */
@Entity
@Table(name = "header_gastos", catalog = "itaid")
public class HeaderGastos implements java.io.Serializable {

	private Integer id;
	private int userid;
	private int headerPedidoId;
	private Date fecha;
	private boolean status;

	public HeaderGastos() {
	}

	public HeaderGastos(int userid, int headerPedidoId, Date fecha, boolean status) {
		this.userid = userid;
		this.headerPedidoId = headerPedidoId;
		this.fecha = fecha;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "header_pedido_id", nullable = false)
	public int getHeaderPedidoId() {
		return this.headerPedidoId;
	}

	public void setHeaderPedidoId(int headerPedidoId) {
		this.headerPedidoId = headerPedidoId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
