package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HeaderPedido generated by hbm2java
 */
@Entity
@Table(name = "header_pedido", catalog = "itaid")
public class HeaderPedido implements java.io.Serializable {

	private Integer id;
	private Date fecha;
	private int userid;
	private int entregaId;
	private Integer departamentoId;
	private boolean status;
	private Integer userBaja;
	private Date fechaBaja;
	private Integer ticket;

	public HeaderPedido() {
	}

	public HeaderPedido(Date fecha, int userid, int entregaId, boolean status) {
		this.fecha = fecha;
		this.userid = userid;
		this.entregaId = entregaId;
		this.status = status;
	}

	public HeaderPedido(Date fecha, int userid, int entregaId, Integer departamentoId, boolean status, Integer userBaja,
			Date fechaBaja, Integer ticket) {
		this.fecha = fecha;
		this.userid = userid;
		this.entregaId = entregaId;
		this.departamentoId = departamentoId;
		this.status = status;
		this.userBaja = userBaja;
		this.fechaBaja = fechaBaja;
		this.ticket = ticket;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "entrega_id", nullable = false)
	public int getEntregaId() {
		return this.entregaId;
	}

	public void setEntregaId(int entregaId) {
		this.entregaId = entregaId;
	}

	@Column(name = "departamento_id")
	public Integer getDepartamentoId() {
		return this.departamentoId;
	}

	public void setDepartamentoId(Integer departamentoId) {
		this.departamentoId = departamentoId;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "user_baja")
	public Integer getUserBaja() {
		return this.userBaja;
	}

	public void setUserBaja(Integer userBaja) {
		this.userBaja = userBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_baja", length = 19)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@Column(name = "ticket")
	public Integer getTicket() {
		return this.ticket;
	}

	public void setTicket(Integer ticket) {
		this.ticket = ticket;
	}

}
