package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImpCatMotivo generated by hbm2java
 */
@Entity
@Table(name = "imp_cat_motivo", catalog = "itaid")
public class ImpCatMotivo implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private String descripcionGeneral;
	private String solucionImp;
	private String codigo;
	private byte status;

	public ImpCatMotivo() {
	}

	public ImpCatMotivo(String descripcion, String descripcionGeneral, String solucionImp, byte status) {
		this.descripcion = descripcion;
		this.descripcionGeneral = descripcionGeneral;
		this.solucionImp = solucionImp;
		this.status = status;
	}

	public ImpCatMotivo(String descripcion, String descripcionGeneral, String solucionImp, String codigo, byte status) {
		this.descripcion = descripcion;
		this.descripcionGeneral = descripcionGeneral;
		this.solucionImp = solucionImp;
		this.codigo = codigo;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "descripcion_general", nullable = false, length = 65535)
	public String getDescripcionGeneral() {
		return this.descripcionGeneral;
	}

	public void setDescripcionGeneral(String descripcionGeneral) {
		this.descripcionGeneral = descripcionGeneral;
	}

	@Column(name = "solucion_imp", nullable = false, length = 65535)
	public String getSolucionImp() {
		return this.solucionImp;
	}

	public void setSolucionImp(String solucionImp) {
		this.solucionImp = solucionImp;
	}

	@Column(name = "codigo", length = 100)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
