package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImpCatSolucion generated by hbm2java
 */
@Entity
@Table(name = "imp_cat_solucion", catalog = "itaid")
public class ImpCatSolucion implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private String descripcionGeneral;
	private boolean status;

	public ImpCatSolucion() {
	}

	public ImpCatSolucion(String descripcion, String descripcionGeneral, boolean status) {
		this.descripcion = descripcion;
		this.descripcionGeneral = descripcionGeneral;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "descripcion_general", nullable = false, length = 65535)
	public String getDescripcionGeneral() {
		return this.descripcionGeneral;
	}

	public void setDescripcionGeneral(String descripcionGeneral) {
		this.descripcionGeneral = descripcionGeneral;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
