package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inmuebles generated by hbm2java
 */
@Entity
@Table(name = "inmuebles", catalog = "itaid")
public class Inmuebles implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Integer numTienda;
	private String ano;
	private BigDecimal rentaInicial;
	private BigDecimal rentaFinal;
	private String numMeses;
	private BigDecimal aportacion;
	private String incrementos;
	private BigDecimal deposito;
	private BigDecimal pagoAnticipado;
	private Integer gracia;
	private Integer interesRetraso;
	private Date fechaFirmaContrato;
	private Date fechaContratoRenovado;
	private Date fechaEntrega;
	private String observaciones;
	private String comentarios;
	private int arrendadoresId;
	private int estadoRentasId;
	private Integer regionRentasId;
	private BigDecimal rentaCorriente;
	private String representanteLegal;
	private String propietario;

	public Inmuebles() {
	}

	public Inmuebles(String nombre, int arrendadoresId, int estadoRentasId) {
		this.nombre = nombre;
		this.arrendadoresId = arrendadoresId;
		this.estadoRentasId = estadoRentasId;
	}

	public Inmuebles(String nombre, Integer numTienda, String ano, BigDecimal rentaInicial, BigDecimal rentaFinal,
			String numMeses, BigDecimal aportacion, String incrementos, BigDecimal deposito, BigDecimal pagoAnticipado,
			Integer gracia, Integer interesRetraso, Date fechaFirmaContrato, Date fechaContratoRenovado,
			Date fechaEntrega, String observaciones, String comentarios, int arrendadoresId, int estadoRentasId,
			Integer regionRentasId, BigDecimal rentaCorriente, String representanteLegal, String propietario) {
		this.nombre = nombre;
		this.numTienda = numTienda;
		this.ano = ano;
		this.rentaInicial = rentaInicial;
		this.rentaFinal = rentaFinal;
		this.numMeses = numMeses;
		this.aportacion = aportacion;
		this.incrementos = incrementos;
		this.deposito = deposito;
		this.pagoAnticipado = pagoAnticipado;
		this.gracia = gracia;
		this.interesRetraso = interesRetraso;
		this.fechaFirmaContrato = fechaFirmaContrato;
		this.fechaContratoRenovado = fechaContratoRenovado;
		this.fechaEntrega = fechaEntrega;
		this.observaciones = observaciones;
		this.comentarios = comentarios;
		this.arrendadoresId = arrendadoresId;
		this.estadoRentasId = estadoRentasId;
		this.regionRentasId = regionRentasId;
		this.rentaCorriente = rentaCorriente;
		this.representanteLegal = representanteLegal;
		this.propietario = propietario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "num_tienda")
	public Integer getNumTienda() {
		return this.numTienda;
	}

	public void setNumTienda(Integer numTienda) {
		this.numTienda = numTienda;
	}

	@Column(name = "ano", length = 45)
	public String getAno() {
		return this.ano;
	}

	public void setAno(String ano) {
		this.ano = ano;
	}

	@Column(name = "renta_inicial", precision = 15)
	public BigDecimal getRentaInicial() {
		return this.rentaInicial;
	}

	public void setRentaInicial(BigDecimal rentaInicial) {
		this.rentaInicial = rentaInicial;
	}

	@Column(name = "renta_final", precision = 15)
	public BigDecimal getRentaFinal() {
		return this.rentaFinal;
	}

	public void setRentaFinal(BigDecimal rentaFinal) {
		this.rentaFinal = rentaFinal;
	}

	@Column(name = "num_meses", length = 25)
	public String getNumMeses() {
		return this.numMeses;
	}

	public void setNumMeses(String numMeses) {
		this.numMeses = numMeses;
	}

	@Column(name = "aportacion", precision = 15)
	public BigDecimal getAportacion() {
		return this.aportacion;
	}

	public void setAportacion(BigDecimal aportacion) {
		this.aportacion = aportacion;
	}

	@Column(name = "incrementos", length = 45)
	public String getIncrementos() {
		return this.incrementos;
	}

	public void setIncrementos(String incrementos) {
		this.incrementos = incrementos;
	}

	@Column(name = "deposito", precision = 15)
	public BigDecimal getDeposito() {
		return this.deposito;
	}

	public void setDeposito(BigDecimal deposito) {
		this.deposito = deposito;
	}

	@Column(name = "pago_anticipado", precision = 15)
	public BigDecimal getPagoAnticipado() {
		return this.pagoAnticipado;
	}

	public void setPagoAnticipado(BigDecimal pagoAnticipado) {
		this.pagoAnticipado = pagoAnticipado;
	}

	@Column(name = "gracia")
	public Integer getGracia() {
		return this.gracia;
	}

	public void setGracia(Integer gracia) {
		this.gracia = gracia;
	}

	@Column(name = "interes_retraso")
	public Integer getInteresRetraso() {
		return this.interesRetraso;
	}

	public void setInteresRetraso(Integer interesRetraso) {
		this.interesRetraso = interesRetraso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_firma_contrato", length = 10)
	public Date getFechaFirmaContrato() {
		return this.fechaFirmaContrato;
	}

	public void setFechaFirmaContrato(Date fechaFirmaContrato) {
		this.fechaFirmaContrato = fechaFirmaContrato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_contrato_renovado", length = 10)
	public Date getFechaContratoRenovado() {
		return this.fechaContratoRenovado;
	}

	public void setFechaContratoRenovado(Date fechaContratoRenovado) {
		this.fechaContratoRenovado = fechaContratoRenovado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_entrega", length = 10)
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "comentarios", length = 250)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "arrendadores_id", nullable = false)
	public int getArrendadoresId() {
		return this.arrendadoresId;
	}

	public void setArrendadoresId(int arrendadoresId) {
		this.arrendadoresId = arrendadoresId;
	}

	@Column(name = "estado_rentas_id", nullable = false)
	public int getEstadoRentasId() {
		return this.estadoRentasId;
	}

	public void setEstadoRentasId(int estadoRentasId) {
		this.estadoRentasId = estadoRentasId;
	}

	@Column(name = "region_rentas_id")
	public Integer getRegionRentasId() {
		return this.regionRentasId;
	}

	public void setRegionRentasId(Integer regionRentasId) {
		this.regionRentasId = regionRentasId;
	}

	@Column(name = "renta_corriente", precision = 15)
	public BigDecimal getRentaCorriente() {
		return this.rentaCorriente;
	}

	public void setRentaCorriente(BigDecimal rentaCorriente) {
		this.rentaCorriente = rentaCorriente;
	}

	@Column(name = "representante_legal", length = 120)
	public String getRepresentanteLegal() {
		return this.representanteLegal;
	}

	public void setRepresentanteLegal(String representanteLegal) {
		this.representanteLegal = representanteLegal;
	}

	@Column(name = "propietario", length = 120)
	public String getPropietario() {
		return this.propietario;
	}

	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

}
