package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name = "inventario", catalog = "itaid")
public class Inventario implements java.io.Serializable {

	private InventarioId id;

	public Inventario() {
	}

	public Inventario(InventarioId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "activo", column = @Column(name = "activo", length = 72)),
			@AttributeOverride(name = "serie", column = @Column(name = "serie", length = 24)),
			@AttributeOverride(name = "tag", column = @Column(name = "tag", length = 20)),
			@AttributeOverride(name = "factura", column = @Column(name = "factura", nullable = false, length = 8)),
			@AttributeOverride(name = "costo", column = @Column(name = "costo", nullable = false, precision = 7)),
			@AttributeOverride(name = "asignado", column = @Column(name = "asignado")),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo", nullable = false, length = 12)),
			@AttributeOverride(name = "desde", column = @Column(name = "desde", nullable = false, length = 10)) })
	public InventarioId getId() {
		return this.id;
	}

	public void setId(InventarioId id) {
		this.id = id;
	}

}
