package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KeysOvpn generated by hbm2java
 */
@Entity
@Table(name = "keys_ovpn", catalog = "itaid")
public class KeysOvpn implements java.io.Serializable {

	private Integer id;
	private int region;
	private int tienda;
	private String tclave;
	private String caja;
	private int userid;
	private Date fecha;
	private boolean status;

	public KeysOvpn() {
	}

	public KeysOvpn(int region, int tienda, String tclave, String caja, int userid, Date fecha, boolean status) {
		this.region = region;
		this.tienda = tienda;
		this.tclave = tclave;
		this.caja = caja;
		this.userid = userid;
		this.fecha = fecha;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "region", nullable = false)
	public int getRegion() {
		return this.region;
	}

	public void setRegion(int region) {
		this.region = region;
	}

	@Column(name = "tienda", nullable = false)
	public int getTienda() {
		return this.tienda;
	}

	public void setTienda(int tienda) {
		this.tienda = tienda;
	}

	@Column(name = "tclave", nullable = false, length = 5)
	public String getTclave() {
		return this.tclave;
	}

	public void setTclave(String tclave) {
		this.tclave = tclave;
	}

	@Column(name = "caja", nullable = false, length = 5)
	public String getCaja() {
		return this.caja;
	}

	public void setCaja(String caja) {
		this.caja = caja;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
