package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogFacturas generated by hbm2java
 */
@Entity
@Table(name = "log_facturas", catalog = "itaid")
public class LogFacturas implements java.io.Serializable {

	private Integer id;
	private int facturaElectroArrendadorId;
	private int estadoRentasId;
	private Date fecha;

	public LogFacturas() {
	}

	public LogFacturas(int facturaElectroArrendadorId, int estadoRentasId) {
		this.facturaElectroArrendadorId = facturaElectroArrendadorId;
		this.estadoRentasId = estadoRentasId;
	}

	public LogFacturas(int facturaElectroArrendadorId, int estadoRentasId, Date fecha) {
		this.facturaElectroArrendadorId = facturaElectroArrendadorId;
		this.estadoRentasId = estadoRentasId;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "factura_electro_arrendador_id", nullable = false)
	public int getFacturaElectroArrendadorId() {
		return this.facturaElectroArrendadorId;
	}

	public void setFacturaElectroArrendadorId(int facturaElectroArrendadorId) {
		this.facturaElectroArrendadorId = facturaElectroArrendadorId;
	}

	@Column(name = "estado_rentas_id", nullable = false)
	public int getEstadoRentasId() {
		return this.estadoRentasId;
	}

	public void setEstadoRentasId(int estadoRentasId) {
		this.estadoRentasId = estadoRentasId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
