package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pbcatfmt generated by hbm2java
 */
@Entity
@Table(name = "pbcatfmt", catalog = "itaid", uniqueConstraints = @UniqueConstraint(columnNames = "pbf_name"))
public class Pbcatfmt implements java.io.Serializable {

	private PbcatfmtId id;

	public Pbcatfmt() {
	}

	public Pbcatfmt(PbcatfmtId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pbfName", column = @Column(name = "pbf_name", unique = true, nullable = false, length = 30)),
			@AttributeOverride(name = "pbfFrmt", column = @Column(name = "pbf_frmt", length = 254)),
			@AttributeOverride(name = "pbfType", column = @Column(name = "pbf_type")),
			@AttributeOverride(name = "pbfCntr", column = @Column(name = "pbf_cntr")) })
	public PbcatfmtId getId() {
		return this.id;
	}

	public void setId(PbcatfmtId id) {
		this.id = id;
	}

}
