package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pbcatvld generated by hbm2java
 */
@Entity
@Table(name = "pbcatvld", catalog = "itaid", uniqueConstraints = @UniqueConstraint(columnNames = "pbv_name"))
public class Pbcatvld implements java.io.Serializable {

	private PbcatvldId id;

	public Pbcatvld() {
	}

	public Pbcatvld(PbcatvldId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pbvName", column = @Column(name = "pbv_name", unique = true, nullable = false, length = 30)),
			@AttributeOverride(name = "pbvVald", column = @Column(name = "pbv_vald", length = 254)),
			@AttributeOverride(name = "pbvType", column = @Column(name = "pbv_type")),
			@AttributeOverride(name = "pbvCntr", column = @Column(name = "pbv_cntr")),
			@AttributeOverride(name = "pbvMsg", column = @Column(name = "pbv_msg", length = 254)) })
	public PbcatvldId getId() {
		return this.id;
	}

	public void setId(PbcatvldId id) {
		this.id = id;
	}

}
