package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pbcattbl generated by hbm2java
 */
@Entity
@Table(name = "pbcattbl", catalog = "itaid", uniqueConstraints = @UniqueConstraint(columnNames = { "pbt_tnam",
		"pbt_ownr" }))
public class Pbcattbl implements java.io.Serializable {

	private PbcattblId id;

	public Pbcattbl() {
	}

	public Pbcattbl(PbcattblId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pbtTnam", column = @Column(name = "pbt_tnam", nullable = false, length = 193)),
			@AttributeOverride(name = "pbtTid", column = @Column(name = "pbt_tid")),
			@AttributeOverride(name = "pbtOwnr", column = @Column(name = "pbt_ownr", nullable = false, length = 193)),
			@AttributeOverride(name = "pbdFhgt", column = @Column(name = "pbd_fhgt")),
			@AttributeOverride(name = "pbdFwgt", column = @Column(name = "pbd_fwgt")),
			@AttributeOverride(name = "pbdFitl", column = @Column(name = "pbd_fitl", length = 1)),
			@AttributeOverride(name = "pbdFunl", column = @Column(name = "pbd_funl", length = 1)),
			@AttributeOverride(name = "pbdFchr", column = @Column(name = "pbd_fchr")),
			@AttributeOverride(name = "pbdFptc", column = @Column(name = "pbd_fptc")),
			@AttributeOverride(name = "pbdFfce", column = @Column(name = "pbd_ffce", length = 18)),
			@AttributeOverride(name = "pbhFhgt", column = @Column(name = "pbh_fhgt")),
			@AttributeOverride(name = "pbhFwgt", column = @Column(name = "pbh_fwgt")),
			@AttributeOverride(name = "pbhFitl", column = @Column(name = "pbh_fitl", length = 1)),
			@AttributeOverride(name = "pbhFunl", column = @Column(name = "pbh_funl", length = 1)),
			@AttributeOverride(name = "pbhFchr", column = @Column(name = "pbh_fchr")),
			@AttributeOverride(name = "pbhFptc", column = @Column(name = "pbh_fptc")),
			@AttributeOverride(name = "pbhFfce", column = @Column(name = "pbh_ffce", length = 18)),
			@AttributeOverride(name = "pblFhgt", column = @Column(name = "pbl_fhgt")),
			@AttributeOverride(name = "pblFwgt", column = @Column(name = "pbl_fwgt")),
			@AttributeOverride(name = "pblFitl", column = @Column(name = "pbl_fitl", length = 1)),
			@AttributeOverride(name = "pblFunl", column = @Column(name = "pbl_funl", length = 1)),
			@AttributeOverride(name = "pblFchr", column = @Column(name = "pbl_fchr")),
			@AttributeOverride(name = "pblFptc", column = @Column(name = "pbl_fptc")),
			@AttributeOverride(name = "pblFfce", column = @Column(name = "pbl_ffce", length = 18)),
			@AttributeOverride(name = "pbtCmnt", column = @Column(name = "pbt_cmnt", length = 254)) })
	public PbcattblId getId() {
		return this.id;
	}

	public void setId(PbcattblId id) {
		this.id = id;
	}

}
