package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pbcatcol generated by hbm2java
 */
@Entity
@Table(name = "pbcatcol", catalog = "itaid", uniqueConstraints = @UniqueConstraint(columnNames = { "pbc_tnam",
		"pbc_ownr", "pbc_cnam" }))
public class Pbcatcol implements java.io.Serializable {

	private PbcatcolId id;

	public Pbcatcol() {
	}

	public Pbcatcol(PbcatcolId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pbcTnam", column = @Column(name = "pbc_tnam", nullable = false, length = 193)),
			@AttributeOverride(name = "pbcTid", column = @Column(name = "pbc_tid")),
			@AttributeOverride(name = "pbcOwnr", column = @Column(name = "pbc_ownr", nullable = false, length = 193)),
			@AttributeOverride(name = "pbcCnam", column = @Column(name = "pbc_cnam", nullable = false, length = 193)),
			@AttributeOverride(name = "pbcCid", column = @Column(name = "pbc_cid")),
			@AttributeOverride(name = "pbcLabl", column = @Column(name = "pbc_labl", length = 254)),
			@AttributeOverride(name = "pbcLpos", column = @Column(name = "pbc_lpos")),
			@AttributeOverride(name = "pbcHdr", column = @Column(name = "pbc_hdr", length = 254)),
			@AttributeOverride(name = "pbcHpos", column = @Column(name = "pbc_hpos")),
			@AttributeOverride(name = "pbcJtfy", column = @Column(name = "pbc_jtfy")),
			@AttributeOverride(name = "pbcMask", column = @Column(name = "pbc_mask", length = 31)),
			@AttributeOverride(name = "pbcCase", column = @Column(name = "pbc_case")),
			@AttributeOverride(name = "pbcHght", column = @Column(name = "pbc_hght")),
			@AttributeOverride(name = "pbcWdth", column = @Column(name = "pbc_wdth")),
			@AttributeOverride(name = "pbcPtrn", column = @Column(name = "pbc_ptrn", length = 31)),
			@AttributeOverride(name = "pbcBmap", column = @Column(name = "pbc_bmap", length = 1)),
			@AttributeOverride(name = "pbcInit", column = @Column(name = "pbc_init", length = 254)),
			@AttributeOverride(name = "pbcCmnt", column = @Column(name = "pbc_cmnt", length = 254)),
			@AttributeOverride(name = "pbcEdit", column = @Column(name = "pbc_edit", length = 31)),
			@AttributeOverride(name = "pbcTag", column = @Column(name = "pbc_tag", length = 254)) })
	public PbcatcolId getId() {
		return this.id;
	}

	public void setId(PbcatcolId id) {
		this.id = id;
	}

}
