package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name = "pedidos", catalog = "itaid")
public class Pedidos implements java.io.Serializable {

	private Integer id;
	private int cantidad;
	private int cantidadRecibida;
	private int activomodeloId;
	private int headerPedidoId;
	private String folio3b;
	private int tipoMonedaId;
	private BigDecimal costo;
	private int proveedorId;
	private String factura;
	private Date fechacompra;
	private int activoestadoId;
	private Integer entregaId;
	private Date fechaasignacion;
	private Date fechaentrega;
	private String comentarios;
	private String observaciones;
	private byte ordencompra;
	private Boolean status;
	private Boolean solicitudpago;
	private Integer pedidoIdKit;

	public Pedidos() {
	}

	public Pedidos(int cantidad, int cantidadRecibida, int activomodeloId, int headerPedidoId, String folio3b,
			int tipoMonedaId, BigDecimal costo, int proveedorId, String factura, Date fechacompra, int activoestadoId,
			Date fechaentrega, String comentarios, String observaciones, byte ordencompra) {
		this.cantidad = cantidad;
		this.cantidadRecibida = cantidadRecibida;
		this.activomodeloId = activomodeloId;
		this.headerPedidoId = headerPedidoId;
		this.folio3b = folio3b;
		this.tipoMonedaId = tipoMonedaId;
		this.costo = costo;
		this.proveedorId = proveedorId;
		this.factura = factura;
		this.fechacompra = fechacompra;
		this.activoestadoId = activoestadoId;
		this.fechaentrega = fechaentrega;
		this.comentarios = comentarios;
		this.observaciones = observaciones;
		this.ordencompra = ordencompra;
	}

	public Pedidos(int cantidad, int cantidadRecibida, int activomodeloId, int headerPedidoId, String folio3b,
			int tipoMonedaId, BigDecimal costo, int proveedorId, String factura, Date fechacompra, int activoestadoId,
			Integer entregaId, Date fechaasignacion, Date fechaentrega, String comentarios, String observaciones,
			byte ordencompra, Boolean status, Boolean solicitudpago, Integer pedidoIdKit) {
		this.cantidad = cantidad;
		this.cantidadRecibida = cantidadRecibida;
		this.activomodeloId = activomodeloId;
		this.headerPedidoId = headerPedidoId;
		this.folio3b = folio3b;
		this.tipoMonedaId = tipoMonedaId;
		this.costo = costo;
		this.proveedorId = proveedorId;
		this.factura = factura;
		this.fechacompra = fechacompra;
		this.activoestadoId = activoestadoId;
		this.entregaId = entregaId;
		this.fechaasignacion = fechaasignacion;
		this.fechaentrega = fechaentrega;
		this.comentarios = comentarios;
		this.observaciones = observaciones;
		this.ordencompra = ordencompra;
		this.status = status;
		this.solicitudpago = solicitudpago;
		this.pedidoIdKit = pedidoIdKit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "cantidad_recibida", nullable = false)
	public int getCantidadRecibida() {
		return this.cantidadRecibida;
	}

	public void setCantidadRecibida(int cantidadRecibida) {
		this.cantidadRecibida = cantidadRecibida;
	}

	@Column(name = "activomodelo_id", nullable = false)
	public int getActivomodeloId() {
		return this.activomodeloId;
	}

	public void setActivomodeloId(int activomodeloId) {
		this.activomodeloId = activomodeloId;
	}

	@Column(name = "header_pedido_id", nullable = false)
	public int getHeaderPedidoId() {
		return this.headerPedidoId;
	}

	public void setHeaderPedidoId(int headerPedidoId) {
		this.headerPedidoId = headerPedidoId;
	}

	@Column(name = "folio3b", nullable = false, length = 128)
	public String getFolio3b() {
		return this.folio3b;
	}

	public void setFolio3b(String folio3b) {
		this.folio3b = folio3b;
	}

	@Column(name = "tipo_moneda_id", nullable = false)
	public int getTipoMonedaId() {
		return this.tipoMonedaId;
	}

	public void setTipoMonedaId(int tipoMonedaId) {
		this.tipoMonedaId = tipoMonedaId;
	}

	@Column(name = "costo", nullable = false, precision = 7)
	public BigDecimal getCosto() {
		return this.costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

	@Column(name = "proveedor_id", nullable = false)
	public int getProveedorId() {
		return this.proveedorId;
	}

	public void setProveedorId(int proveedorId) {
		this.proveedorId = proveedorId;
	}

	@Column(name = "factura", nullable = false)
	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacompra", nullable = false, length = 10)
	public Date getFechacompra() {
		return this.fechacompra;
	}

	public void setFechacompra(Date fechacompra) {
		this.fechacompra = fechacompra;
	}

	@Column(name = "activoestado_id", nullable = false)
	public int getActivoestadoId() {
		return this.activoestadoId;
	}

	public void setActivoestadoId(int activoestadoId) {
		this.activoestadoId = activoestadoId;
	}

	@Column(name = "entrega_id")
	public Integer getEntregaId() {
		return this.entregaId;
	}

	public void setEntregaId(Integer entregaId) {
		this.entregaId = entregaId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaasignacion", length = 10)
	public Date getFechaasignacion() {
		return this.fechaasignacion;
	}

	public void setFechaasignacion(Date fechaasignacion) {
		this.fechaasignacion = fechaasignacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaentrega", nullable = false, length = 10)
	public Date getFechaentrega() {
		return this.fechaentrega;
	}

	public void setFechaentrega(Date fechaentrega) {
		this.fechaentrega = fechaentrega;
	}

	@Column(name = "comentarios", nullable = false, length = 65535)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "observaciones", nullable = false)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "ordencompra", nullable = false)
	public byte getOrdencompra() {
		return this.ordencompra;
	}

	public void setOrdencompra(byte ordencompra) {
		this.ordencompra = ordencompra;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "solicitudpago")
	public Boolean getSolicitudpago() {
		return this.solicitudpago;
	}

	public void setSolicitudpago(Boolean solicitudpago) {
		this.solicitudpago = solicitudpago;
	}

	@Column(name = "pedido_id_kit")
	public Integer getPedidoIdKit() {
		return this.pedidoIdKit;
	}

	public void setPedidoIdKit(Integer pedidoIdKit) {
		this.pedidoIdKit = pedidoIdKit;
	}

}
