package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "itaid")
public class Perfil implements java.io.Serializable {

	private int id;
	private String nombre;
	private String descripcion;
	private Boolean oculto;

	public Perfil() {
	}

	public Perfil(int id, String nombre, String descripcion) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Perfil(int id, String nombre, String descripcion, Boolean oculto) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.oculto = oculto;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "oculto")
	public Boolean getOculto() {
		return this.oculto;
	}

	public void setOculto(Boolean oculto) {
		this.oculto = oculto;
	}

}
