package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfileSolicitud generated by hbm2java
 */
@Entity
@Table(name = "profile_solicitud", catalog = "itaid")
public class ProfileSolicitud implements java.io.Serializable {

	private Integer id;
	private int departamentoId;
	private String descripcion;
	private int userCreate;
	private Date dateCreate;
	private boolean status;

	public ProfileSolicitud() {
	}

	public ProfileSolicitud(int departamentoId, String descripcion, int userCreate, Date dateCreate, boolean status) {
		this.departamentoId = departamentoId;
		this.descripcion = descripcion;
		this.userCreate = userCreate;
		this.dateCreate = dateCreate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "departamento_id", nullable = false)
	public int getDepartamentoId() {
		return this.departamentoId;
	}

	public void setDepartamentoId(int departamentoId) {
		this.departamentoId = departamentoId;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "user_create", nullable = false)
	public int getUserCreate() {
		return this.userCreate;
	}

	public void setUserCreate(int userCreate) {
		this.userCreate = userCreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_create", nullable = false, length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
