package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProfileSolicitudPeriodo generated by hbm2java
 */
@Entity
@Table(name = "profile_solicitud_periodo", catalog = "itaid")
public class ProfileSolicitudPeriodo implements java.io.Serializable {

	private Integer id;
	private int profileId;
	private Byte diaSemana;
	private Integer diaMes;
	private boolean status;

	public ProfileSolicitudPeriodo() {
	}

	public ProfileSolicitudPeriodo(int profileId, boolean status) {
		this.profileId = profileId;
		this.status = status;
	}

	public ProfileSolicitudPeriodo(int profileId, Byte diaSemana, Integer diaMes, boolean status) {
		this.profileId = profileId;
		this.diaSemana = diaSemana;
		this.diaMes = diaMes;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "profile_id", nullable = false)
	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	@Column(name = "dia_semana")
	public Byte getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(Byte diaSemana) {
		this.diaSemana = diaSemana;
	}

	@Column(name = "dia_mes")
	public Integer getDiaMes() {
		return this.diaMes;
	}

	public void setDiaMes(Integer diaMes) {
		this.diaMes = diaMes;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
