package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProyectoTarea generated by hbm2java
 */
@Entity
@Table(name = "proyecto_tarea", catalog = "itaid")
public class ProyectoTarea implements java.io.Serializable {

	private int id;
	private Integer orden;
	private int proyectoId;
	private int proyectofaseId;
	private String tarea;
	private String descripcion;
	private String entregable;
	private int prioridad;
	private Integer tareaanteriorId;
	private Date fechainicio;
	private Date fechafinorig;
	private Date fechafinact;
	private Integer diashabiles;
	private short avance;
	private Integer vobousuarioId;
	private Date vobofecha;
	private String observaciones;
	private int tareaestadoId;
	private int tecnicoId;

	public ProyectoTarea() {
	}

	public ProyectoTarea(int id, int proyectoId, int proyectofaseId, String tarea, String descripcion, int prioridad,
			Date fechainicio, Date fechafinorig, Date fechafinact, short avance, int tareaestadoId, int tecnicoId) {
		this.id = id;
		this.proyectoId = proyectoId;
		this.proyectofaseId = proyectofaseId;
		this.tarea = tarea;
		this.descripcion = descripcion;
		this.prioridad = prioridad;
		this.fechainicio = fechainicio;
		this.fechafinorig = fechafinorig;
		this.fechafinact = fechafinact;
		this.avance = avance;
		this.tareaestadoId = tareaestadoId;
		this.tecnicoId = tecnicoId;
	}

	public ProyectoTarea(int id, Integer orden, int proyectoId, int proyectofaseId, String tarea, String descripcion,
			String entregable, int prioridad, Integer tareaanteriorId, Date fechainicio, Date fechafinorig,
			Date fechafinact, Integer diashabiles, short avance, Integer vobousuarioId, Date vobofecha,
			String observaciones, int tareaestadoId, int tecnicoId) {
		this.id = id;
		this.orden = orden;
		this.proyectoId = proyectoId;
		this.proyectofaseId = proyectofaseId;
		this.tarea = tarea;
		this.descripcion = descripcion;
		this.entregable = entregable;
		this.prioridad = prioridad;
		this.tareaanteriorId = tareaanteriorId;
		this.fechainicio = fechainicio;
		this.fechafinorig = fechafinorig;
		this.fechafinact = fechafinact;
		this.diashabiles = diashabiles;
		this.avance = avance;
		this.vobousuarioId = vobousuarioId;
		this.vobofecha = vobofecha;
		this.observaciones = observaciones;
		this.tareaestadoId = tareaestadoId;
		this.tecnicoId = tecnicoId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "proyecto_id", nullable = false)
	public int getProyectoId() {
		return this.proyectoId;
	}

	public void setProyectoId(int proyectoId) {
		this.proyectoId = proyectoId;
	}

	@Column(name = "proyectofase_id", nullable = false)
	public int getProyectofaseId() {
		return this.proyectofaseId;
	}

	public void setProyectofaseId(int proyectofaseId) {
		this.proyectofaseId = proyectofaseId;
	}

	@Column(name = "tarea", nullable = false, length = 50)
	public String getTarea() {
		return this.tarea;
	}

	public void setTarea(String tarea) {
		this.tarea = tarea;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "entregable", length = 35)
	public String getEntregable() {
		return this.entregable;
	}

	public void setEntregable(String entregable) {
		this.entregable = entregable;
	}

	@Column(name = "prioridad", nullable = false)
	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

	@Column(name = "tareaanterior_id")
	public Integer getTareaanteriorId() {
		return this.tareaanteriorId;
	}

	public void setTareaanteriorId(Integer tareaanteriorId) {
		this.tareaanteriorId = tareaanteriorId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechainicio", nullable = false, length = 10)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafinorig", nullable = false, length = 10)
	public Date getFechafinorig() {
		return this.fechafinorig;
	}

	public void setFechafinorig(Date fechafinorig) {
		this.fechafinorig = fechafinorig;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafinact", nullable = false, length = 10)
	public Date getFechafinact() {
		return this.fechafinact;
	}

	public void setFechafinact(Date fechafinact) {
		this.fechafinact = fechafinact;
	}

	@Column(name = "diashabiles")
	public Integer getDiashabiles() {
		return this.diashabiles;
	}

	public void setDiashabiles(Integer diashabiles) {
		this.diashabiles = diashabiles;
	}

	@Column(name = "avance", nullable = false, precision = 3, scale = 0)
	public short getAvance() {
		return this.avance;
	}

	public void setAvance(short avance) {
		this.avance = avance;
	}

	@Column(name = "vobousuario_id")
	public Integer getVobousuarioId() {
		return this.vobousuarioId;
	}

	public void setVobousuarioId(Integer vobousuarioId) {
		this.vobousuarioId = vobousuarioId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vobofecha", length = 10)
	public Date getVobofecha() {
		return this.vobofecha;
	}

	public void setVobofecha(Date vobofecha) {
		this.vobofecha = vobofecha;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "tareaestado_id", nullable = false)
	public int getTareaestadoId() {
		return this.tareaestadoId;
	}

	public void setTareaestadoId(int tareaestadoId) {
		this.tareaestadoId = tareaestadoId;
	}

	@Column(name = "tecnico_id", nullable = false)
	public int getTecnicoId() {
		return this.tecnicoId;
	}

	public void setTecnicoId(int tecnicoId) {
		this.tecnicoId = tecnicoId;
	}

}
