package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReportexdiaBkp generated by hbm2java
 */
@Entity
@Table(name = "reportexdia_bkp", catalog = "itaid")
public class ReportexdiaBkp implements java.io.Serializable {

	private ReportexdiaBkpId id;

	public ReportexdiaBkp() {
	}

	public ReportexdiaBkp(ReportexdiaBkpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "fecha", column = @Column(name = "Fecha", length = 10)),
			@AttributeOverride(name = "problema", column = @Column(name = "Problema", nullable = false)),
			@AttributeOverride(name = "origen", column = @Column(name = "Origen", nullable = false, length = 25)),
			@AttributeOverride(name = "solucion", column = @Column(name = "Solucion", nullable = false)),
			@AttributeOverride(name = "cantidad", column = @Column(name = "Cantidad", nullable = false)) })
	public ReportexdiaBkpId getId() {
		return this.id;
	}

	public void setId(ReportexdiaBkpId id) {
		this.id = id;
	}

}
