package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Satusuario generated by hbm2java
 */
@Entity
@Table(name = "satusuario", catalog = "itaid")
public class Satusuario implements java.io.Serializable {

	private int nempleado;
	private String ulogin;
	private String unombre;
	private String uapellidop;
	private String uapellidom;
	private int ptoclave;
	private String uclavegrupo;
	private int iddeptoalmacen;

	public Satusuario() {
	}

	public Satusuario(int nempleado, String ulogin, String unombre, String uapellidop, String uapellidom, int ptoclave,
			String uclavegrupo, int iddeptoalmacen) {
		this.nempleado = nempleado;
		this.ulogin = ulogin;
		this.unombre = unombre;
		this.uapellidop = uapellidop;
		this.uapellidom = uapellidom;
		this.ptoclave = ptoclave;
		this.uclavegrupo = uclavegrupo;
		this.iddeptoalmacen = iddeptoalmacen;
	}

	@Id

	@Column(name = "nempleado", unique = true, nullable = false)
	public int getNempleado() {
		return this.nempleado;
	}

	public void setNempleado(int nempleado) {
		this.nempleado = nempleado;
	}

	@Column(name = "ulogin", nullable = false, length = 15)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "unombre", nullable = false, length = 20)
	public String getUnombre() {
		return this.unombre;
	}

	public void setUnombre(String unombre) {
		this.unombre = unombre;
	}

	@Column(name = "uapellidop", nullable = false, length = 20)
	public String getUapellidop() {
		return this.uapellidop;
	}

	public void setUapellidop(String uapellidop) {
		this.uapellidop = uapellidop;
	}

	@Column(name = "uapellidom", nullable = false, length = 20)
	public String getUapellidom() {
		return this.uapellidom;
	}

	public void setUapellidom(String uapellidom) {
		this.uapellidom = uapellidom;
	}

	@Column(name = "ptoclave", nullable = false)
	public int getPtoclave() {
		return this.ptoclave;
	}

	public void setPtoclave(int ptoclave) {
		this.ptoclave = ptoclave;
	}

	@Column(name = "uclavegrupo", nullable = false, length = 4)
	public String getUclavegrupo() {
		return this.uclavegrupo;
	}

	public void setUclavegrupo(String uclavegrupo) {
		this.uclavegrupo = uclavegrupo;
	}

	@Column(name = "iddeptoalmacen", nullable = false)
	public int getIddeptoalmacen() {
		return this.iddeptoalmacen;
	}

	public void setIddeptoalmacen(int iddeptoalmacen) {
		this.iddeptoalmacen = iddeptoalmacen;
	}

}
