package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Table10Res generated by hbm2java
 */
@Entity
@Table(name = "table10_res", catalog = "itaid")
public class Table10Res implements java.io.Serializable {

	private Table10ResId id;

	public Table10Res() {
	}

	public Table10Res(Table10ResId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idCategoria", column = @Column(name = "Id Categoria")),
			@AttributeOverride(name = "categoria", column = @Column(name = "Categoria", length = 26)),
			@AttributeOverride(name = "idModelo", column = @Column(name = "Id Modelo", length = 10)),
			@AttributeOverride(name = "modelo", column = @Column(name = "Modelo", length = 23)),
			@AttributeOverride(name = "marca", column = @Column(name = "Marca", length = 22)),
			@AttributeOverride(name = "serie", column = @Column(name = "Serie", length = 24)),
			@AttributeOverride(name = "tagCpu", column = @Column(name = "Tag CPU", length = 7)),
			@AttributeOverride(name = "usuario", column = @Column(name = "Usuario", length = 28)),
			@AttributeOverride(name = "departamento", column = @Column(name = "Departamento", length = 8)),
			@AttributeOverride(name = "usuarioId", column = @Column(name = "usuario_id", length = 8)) })
	public Table10ResId getId() {
		return this.id;
	}

	public void setId(Table10ResId id) {
		this.id = id;
	}

}
