package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipotd generated by hbm2java
 */
@Entity
@Table(name = "tipotd", catalog = "itaid")
public class Tipotd implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;
	private String abreviatura;
	private boolean status;
	private Byte batch48h;

	public Tipotd() {
	}

	public Tipotd(String nombre, boolean status) {
		this.nombre = nombre;
		this.status = status;
	}

	public Tipotd(String nombre, String descripcion, String abreviatura, boolean status, Byte batch48h) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.abreviatura = abreviatura;
		this.status = status;
		this.batch48h = batch48h;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "abreviatura", length = 10)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "batch48h")
	public Byte getBatch48h() {
		return this.batch48h;
	}

	public void setBatch48h(Byte batch48h) {
		this.batch48h = batch48h;
	}

}
