package mx.tiendas3b.tdexpress.entities;
// Generated 6/03/2019 08:16:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name = "zona", catalog = "itaid")
public class Zona implements java.io.Serializable {

	private int zonaid;
	private String zonadesc;
	private String supervisor;
	private Integer useq;
	private int rclave;

	public Zona() {
	}

	public Zona(int zonaid, String zonadesc, int rclave) {
		this.zonaid = zonaid;
		this.zonadesc = zonadesc;
		this.rclave = rclave;
	}

	public Zona(int zonaid, String zonadesc, String supervisor, Integer useq, int rclave) {
		this.zonaid = zonaid;
		this.zonadesc = zonadesc;
		this.supervisor = supervisor;
		this.useq = useq;
		this.rclave = rclave;
	}

	@Id

	@Column(name = "zonaid", unique = true, nullable = false)
	public int getZonaid() {
		return this.zonaid;
	}

	public void setZonaid(int zonaid) {
		this.zonaid = zonaid;
	}

	@Column(name = "zonadesc", nullable = false, length = 254)
	public String getZonadesc() {
		return this.zonadesc;
	}

	public void setZonadesc(String zonadesc) {
		this.zonadesc = zonadesc;
	}

	@Column(name = "supervisor", length = 60)
	public String getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(String supervisor) {
		this.supervisor = supervisor;
	}

	@Column(name = "useq")
	public Integer getUseq() {
		return this.useq;
	}

	public void setUseq(Integer useq) {
		this.useq = useq;
	}

	@Column(name = "rclave", nullable = false)
	public int getRclave() {
		return this.rclave;
	}

	public void setRclave(int rclave) {
		this.rclave = rclave;
	}

}
